Repository kubermatic/machine-controller, pull requests merged in 2018-11, with the labels that each got.

#389 Pass PVLister down to providers Create/Delete
  cmd/controller/main.go
  examples/machine-controller.yaml
  pkg/cloudprovider/cloud/provider.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/controller/machine/machine.go
  test/e2e/provisioning/migrateuidscenario.go
  test/e2e/provisioning/verify.go
Labels: approved, lgtm, release-note-none, size/L

#391 AWS - Add cache for the AMI ID's
  Gopkg.lock
  Gopkg.toml
  pkg/cloudprovider/provider/aws/provider.go
  vendor/github.com/patrickmn/go-cache/CONTRIBUTORS
  vendor/github.com/patrickmn/go-cache/LICENSE
  vendor/github.com/patrickmn/go-cache/cache.go
  vendor/github.com/patrickmn/go-cache/sharded.go
Labels: approved, lgtm, release-note-none, size/XXL

#392 Remove deprecated changed return parameter on cloud provider implementations
  pkg/admission/machines.go
  pkg/cloudprovider/cloud/provider.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  test/e2e/provisioning/migrateuidscenario.go
Labels: approved, lgtm, release-note-none, size/M

#395 Avoid deleting PV-backing vsphere volumes on instance delete
  examples/machine-controller.yaml
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: approved, lgtm, release-note-none, size/M

#396 Minify ignition & gzip cloud-init
  pkg/cloudprovider/provider/aws/provider.go
  pkg/userdata/centos/userdata_test.go
  pkg/userdata/convert/gzip.go
  pkg/userdata/convert/ignition-converter.go
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.golden
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.golden
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.golden
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.golden
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.golden
  pkg/userdata/coreos/userdata.go
  pkg/userdata/coreos/userdata_test.go
  pkg/userdata/ubuntu/userdata_test.go
  pkg/userdata/userdata.go
Labels: approved, lgtm, release-note-none, size/XXL

#398 Cache cloudprovider validation
  examples/machine-controller.yaml
  pkg/admission/machines.go
  pkg/cloudprovider/cache/cloudprovidercache.go
  pkg/cloudprovider/cache/cloudprovidercache_test.go
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/validationwrapper.go
Labels: approved, lgtm, release-note-none, size/L

#402 Enhance doc and clarify openstack tag/metadata
  examples/openstack-machinedeployment.yaml
  pkg/cloudprovider/provider/openstack/provider.go
Labels: approved, lgtm, release-note-none, size/S

#401 Update makefiles for migrating to prow
  Makefile
  hack/ci-e2e-test.sh
  test/tools/integration/Makefile
Labels: approved, lgtm, release-note-none, size/M

#405 Improve local testing
  Makefile
  README.md
  examples/machine-controller.yaml
  test/tools/integration/Makefile
  test/tools/integration/hetzner.tf
  test/tools/integration/provision_master.sh
Labels: approved, lgtm, release-note-none, size/M

#414 Disable vsphere e2e tests
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, lgtm, release-note-none, size/L

#412 Remove creation of Instance profile & Role if not specified
  examples/aws-machinedeployment.yaml
  pkg/cloudprovider/provider/aws/provider.go
  test/e2e/provisioning/testdata/machinedeployment-aws.yaml
Labels: approved, lgtm, release-note-none, size/L

#403 Move region into secret of openstack
  examples/openstack-machinedeployment.yaml
  pkg/cloudprovider/provider/openstack/provider.go
Labels: approved, lgtm, needs-ok-to-test, release-note-none, size/S

#413 remove kubeadm specific RBAC manifests
  examples/machine-controller.yaml
Labels: approved, lgtm, release-note-none, size/M

#385 replace delete with cleanup to ensure proper deletion of all cloud provider resources
  pkg/cloudprovider/cloud/provider.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/validationwrapper.go
  pkg/controller/machine/machine.go
  test/e2e/provisioning/migrateuidscenario.go
Labels: approved, lgtm, release-note-none, size/L

#408 Makefile: fix targets to pass tests
  .circleci/config.yml
  Makefile
  hack/ci-e2e-test.sh
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/tools/integration/Makefile
Labels: approved, lgtm, release-note-none, size/L

#417 Default GIT_TAG variable in Makefile
  Makefile
Labels: approved, lgtm, release-note-none, size/S
