Repository kubermatic/machine-controller, pull requests merged in 2018-12, with the labels that each got.

#423 filter images by name when loading the image from the openstack api
  pkg/cloudprovider/provider/openstack/helper.go
  pkg/cloudprovider/provider/openstack/provider.go
Labels: approved, lgtm, release-note-none, size/S

#425 Allow machineSpec mutation when there is an initializer
  pkg/admission/machines.go
  test/tools/integration/provision_master.sh
Labels: approved, lgtm, release-note-none, size/S

#421 fixes the way we add security groups to an instance (aws)
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, lgtm, release-note-none, size/S

#426 Replace gometalineter with golangci-lint
  .golangci.yml
  Makefile
  cmd/controller/main.go
  gometalinter.json
  pkg/apis/cluster/v1alpha1/migrations/migrations.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/clusterinfo/configmap.go
  pkg/controller/machine/kubeconfig.go
  pkg/controller/machine/machine.go
  pkg/health/readiness.go
  pkg/node/eviction/eviction_test.go
  pkg/providerconfig/types.go
  pkg/providerconfig/types_test.go
  pkg/userdata/centos/userdata_test.go
  pkg/userdata/coreos/userdata_test.go
  pkg/userdata/helper/download_binaries_script.go
  pkg/userdata/helper/kubelet.go
  pkg/userdata/ubuntu/userdata.go
  pkg/userdata/ubuntu/userdata_test.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/verify.go
Labels: approved, lgtm, release-note-none, size/L

#427 Replace 1.9 e2e tests with 1.13
  test/e2e/provisioning/helper.go
  test/tools/integration/provision_master.sh
Labels: approved, lgtm, release-note-none, size/S

#411 Expand cloud configs
  pkg/cloudprovider/provider/aws/cloudconfig.go
  pkg/cloudprovider/provider/aws/cloudconfig_test.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/aws/testdata/simple-config.golden
  pkg/cloudprovider/provider/azure/cloudconfig.go
  pkg/cloudprovider/provider/azure/provider.go
Labels: approved, lgtm, release-note-none, size/L

#428 Update cloud-config structs
  pkg/cloudprovider/provider/azure/cloudconfig.go
  pkg/cloudprovider/provider/openstack/cloudconfig.go
  pkg/cloudprovider/provider/openstack/cloudconfig_test.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/testdata/simple-config.golden
  pkg/cloudprovider/provider/vsphere/cloudconfig.go
  pkg/cloudprovider/provider/vsphere/testdata/2-virtual-centers.golden
  pkg/cloudprovider/provider/vsphere/testdata/simple-config.golden
Labels: approved, lgtm, release-note-none, size/M

#429 Limit node CPUs on VSphere
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: approved, lgtm, release-note, size/XS

#382 Install docker 17.03 via binary and configure logs rotation on all systems via daemon.json
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.golden
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.golden
  pkg/userdata/centos/userdata.go
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.golden
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.golden
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.golden
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.golden
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.golden
  pkg/userdata/coreos/userdata.go
  pkg/userdata/helper/container_runtime.go
  pkg/userdata/helper/download_binaries_script.go
  pkg/userdata/helper/helper.go
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/template_functions.go
  pkg/userdata/helper/testdata/download_binaries_v1.10.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.3.golden
  pkg/userdata/helper/testdata/download_binaries_v1.12.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_cloud-provider-set.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_multiple-dns-servers.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0.golden
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
  pkg/userdata/ubuntu/testdata/openstack.golden
  pkg/userdata/ubuntu/testdata/version-1.10.10.golden
  pkg/userdata/ubuntu/testdata/version-1.11.3.golden
  pkg/userdata/ubuntu/testdata/version-1.12.1.golden
  pkg/userdata/ubuntu/testdata/version-1.9.10.golden
  pkg/userdata/ubuntu/testdata/vsphere.golden
  pkg/userdata/ubuntu/userdata.go
Labels: approved, lgtm, release-note, size/XXL

#434 Fix MachineDeployment defaulting
  pkg/admission/machinedeployments_test.go
  pkg/admission/machinedeployments_validation.go
Labels: approved, lgtm, release-note-none, size/M

#435 add document to describe the provision command
  cmd/provision/README.md
Labels: approved, lgtm, release-note-none, size/M

#436 Use S3 bucket for CI e2e state
  hack/ci-e2e-test.sh
  test/tools/integration/Makefile
  test/tools/integration/cleanup_machines.sh
  test/tools/integration/output.tf
  test/tools/integration/provider.tf.disabled
  test/tools/integration/provision_master.sh
  test/tools/integration/variables.tf
Labels: approved, lgtm, release-note-none, size/M

#437 Revert "Install docker 17.03 via binary and configure logs rotation o…
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.golden
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.golden
  pkg/userdata/centos/userdata.go
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.golden
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.golden
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.golden
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.golden
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.golden
  pkg/userdata/coreos/userdata.go
  pkg/userdata/helper/container_runtime.go
  pkg/userdata/helper/download_binaries_script.go
  pkg/userdata/helper/helper.go
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/template_functions.go
  pkg/userdata/helper/testdata/download_binaries_v1.10.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.3.golden
  pkg/userdata/helper/testdata/download_binaries_v1.12.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_cloud-provider-set.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_multiple-dns-servers.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0.golden
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
  pkg/userdata/ubuntu/testdata/openstack.golden
  pkg/userdata/ubuntu/testdata/version-1.10.10.golden
  pkg/userdata/ubuntu/testdata/version-1.11.3.golden
  pkg/userdata/ubuntu/testdata/version-1.12.1.golden
  pkg/userdata/ubuntu/testdata/version-1.9.10.golden
  pkg/userdata/ubuntu/testdata/vsphere.golden
  pkg/userdata/ubuntu/userdata.go
Labels: approved, lgtm, release-note-none, size/XXL
