Repository kubermatic/machine-controller, pull requests merged in 2018-10, with the labels that each got.

#362 Add a MutatingAdmissionWebook + Defaulting/Validation for MachineDeployment
  .circleci/config.yml
  .gitignore
  Dockerfile
  Gopkg.lock
  Makefile
  README.md
  cmd/webhook/main.go
  examples/machine-controller.yaml
  pkg/admission/admission.go
  pkg/admission/machinedeployments.go
  pkg/admission/machinedeployments_validation.go
  test/tools/integration/provision_master.sh
  vendor/github.com/mattbaird/jsonpatch/LICENSE
  vendor/github.com/mattbaird/jsonpatch/jsonpatch.go
Labels: approved, lgtm, size/XL

#360 simplify clearing of a machine error
  pkg/controller/machine/machine.go
Labels: approved, lgtm, size/M

#367 Add release-note block to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, release-note-none, size/XS

#368 VSphere: Split clone and reconfigure
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.golden
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.golden
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.golden
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.golden
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.golden
  pkg/userdata/coreos/userdata.go
Labels: approved, lgtm, release-note-none, size/L

#369 encode openstack quota errors as terminal errors
  pkg/cloudprovider/provider/openstack/provider.go
Labels: approved, lgtm, release-note, size/M

#370 Fix ini escaping
  Gopkg.lock
  Gopkg.toml
  pkg/cloudprovider/provider/openstack/cloudconfig.go
  pkg/cloudprovider/provider/openstack/cloudconfig_test.go
  pkg/cloudprovider/provider/openstack/testdata/config-with-special-chars.golden
  pkg/cloudprovider/provider/openstack/testdata/simple-config.golden
  pkg/cloudprovider/provider/vsphere/cloudconfig.go
  pkg/cloudprovider/provider/vsphere/cloudconfig_test.go
  pkg/cloudprovider/provider/vsphere/provider_test.go
  pkg/cloudprovider/provider/vsphere/testdata/2-virtual-centers.golden
  pkg/cloudprovider/provider/vsphere/testdata/simple-config.golden
  pkg/ini/escape.go
  pkg/ini/escape_test.go
  vendor/github.com/sethvargo/go-password/LICENSE
  vendor/github.com/sethvargo/go-password/password/generate.go
  vendor/gopkg.in/ini.v1/LICENSE
  vendor/gopkg.in/ini.v1/error.go
  vendor/gopkg.in/ini.v1/file.go
  vendor/gopkg.in/ini.v1/ini.go
  vendor/gopkg.in/ini.v1/key.go
  vendor/gopkg.in/ini.v1/parser.go
  vendor/gopkg.in/ini.v1/section.go
  vendor/gopkg.in/ini.v1/struct.go
Labels: approved, lgtm, release-note-none, size/XXL

#372 Never override the hostname on AWS nodes
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.golden
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.golden
  pkg/userdata/centos/userdata.go
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.golden
  pkg/userdata/coreos/userdata.go
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/testdata/kublet_systemd_unit_cloud-provider-set.golden
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
  pkg/userdata/ubuntu/testdata/openstack.golden
  pkg/userdata/ubuntu/testdata/version-1.10.10.golden
  pkg/userdata/ubuntu/testdata/version-1.11.3.golden
  pkg/userdata/ubuntu/testdata/version-1.12.1.golden
  pkg/userdata/ubuntu/testdata/version-1.9.10.golden
  pkg/userdata/ubuntu/testdata/vsphere.golden
  pkg/userdata/ubuntu/userdata.go
Labels: approved, lgtm, release-note-none, size/M

#373 Fix Openstack Delete err return
  pkg/cloudprovider/provider/openstack/provider.go
  test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: approved, lgtm, release-note-none, size/S

#374 Fix nullpointer dereference in openstack helper.go
  pkg/cloudprovider/provider/openstack/helper.go
Labels: approved, lgtm, needs-ok-to-test, release-note, size/XS

#375 Migrate machine UIDs
  cmd/controller/main.go
  pkg/apis/cluster/v1alpha1/migrations/migrations.go
  pkg/cloudprovider/cloud/provider.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/create_delete_resources.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/controller/machine/machine.go
Labels: approved, lgtm, release-note, size/L

#378 Test cloudproviders MigrateUID
  .circleci/config.yml
  pkg/cloudprovider/provider/vsphere/provider.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/migrateuidscenario.go
Labels: approved, lgtm, release-note-none, size/L

#380 [AWS] always use latest AMI ID
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, lgtm, release-note, size/L

#386 Make MigrateUID scenario concurrency-safe
  pkg/apis/cluster/v1alpha1/migrations/migrations.go
  pkg/controller/machine/machine.go
  pkg/controller/machine/machine_test.go
  test/e2e/provisioning/migrateuidscenario.go
Labels: approved, lgtm, release-note-none, size/M
