Repository kubermatic/machine-controller, pull requests merged in 2019-06, with the labels that each got.

#553 Set cluster-autoscaler annotation on nodes
  pkg/controller/machine/machine.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#557 Update cluster-api to 2ec456177c0e8f0a903f4e746d44baaae54cc591
  Gopkg.lock
  Gopkg.toml
  pkg/apis/cluster/v1alpha1/conversions/conversions.go
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/aws.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/azure.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/digitalocean.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/hetzner.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/linode.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/openstack.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/vsphere-static-ip.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/vsphere.yaml
  vendor/sigs.k8s.io/cluster-api/logos/LICENSE.md
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/cluster_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineclass_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machinedeployment_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/machinedeployment_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/rolling.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/sync.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/delete_policy.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/machineset_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/status.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/noderefutil/util.go
  vendor/sigs.k8s.io/cluster-api/pkg/util/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#558 Don't render null ssh key into cloud-init
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/coreos/provider.go
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
  pkg/userdata/helper/download_binaries_script.go
  pkg/userdata/helper/testdata/download_binaries_v1.10.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.3.golden
  pkg/userdata/helper/testdata/download_binaries_v1.12.0.golden
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#562 Skip eviction if there is no possible target
  pkg/controller/machine/machine.go
  pkg/controller/machine/machine_test.go
  pkg/node/eviction/eviction.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#552 vSphere: add missing fields in example
  examples/vsphere-machinedeployment.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S, team/lifecycle

#560 Use omitempty for providerConfigs
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/packet/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#565 Add NodeTags to GCE CloudConfig
  pkg/cloudprovider/provider/gce/cloudconfig.go
  pkg/cloudprovider/provider/gce/cloudconfig_test.go
  pkg/cloudprovider/provider/gce/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#566 Dont set --allow-privileged on kubernetes > 1.14 as it got removed
  pkg/userdata/coreos/provider_test.go
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/helper/kubelet.go
  test/e2e/provisioning/helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#531 VSphere: Use the machine UID for identification instead of name
  pkg/cloudprovider/errors/errors.go
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#567 Fix placeholder to project name
  CONTRIBUTING.md
  hack/boilerplate/test/fail.go
  hack/boilerplate/test/fail.py
  hack/boilerplate/test/pass.go
  hack/boilerplate/test/pass.py
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#571 Set environmentfile for kubelet
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/coreos/provider.go
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-proxy.yaml
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/testdata/kublet_systemd_unit_cloud-provider-set.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_multiple-dns-servers.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_pause-image-set.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0.golden
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#569 typo in vmSize for azure provider.go
  pkg/cloudprovider/provider/azure/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#573 Fix conformance tests for CentOS
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS, team/lifecycle

#576 Hcloud: Allow configuring labels
  examples/hetzner-machinedeployment.yaml
  pkg/cloudprovider/provider/hetzner/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#577 Requeue machines after evictions were created instead of blocking
  pkg/controller/machine/machine.go
  pkg/node/eviction/eviction.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#561 Add the howto-provider to the README
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#578 Fix rendering of TOC in readme
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#579 Make Openstack root disk size configurable
  Gopkg.lock
  examples/openstack-machinedeployment.yaml
  pkg/cloudprovider/provider/openstack/provider.go
  vendor/github.com/gophercloud/gophercloud/auth_options.go
  vendor/github.com/gophercloud/gophercloud/auth_result.go
  vendor/github.com/gophercloud/gophercloud/doc.go
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/microversions.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/regions/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/utils/base_endpoint.go
  vendor/github.com/gophercloud/gophercloud/pagination/pager.go
  vendor/github.com/gophercloud/gophercloud/params.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/gophercloud/gophercloud/results.go
  vendor/github.com/gophercloud/gophercloud/service_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/lifecycle
