Repository kubermatic/machine-controller, pull requests merged in 2019-08, with the labels that each got.

#595 Kubevirt provider: Use PVCs to back machines
  Gopkg.lock
  Gopkg.toml
  docs/kubevirt.md
  examples/cdi-operator-cr.yaml
  examples/cdi-operator.yaml
  examples/kubevirt-0.10.0.yaml
  examples/kubevirt-cr.yaml
  examples/kubevirt-local-mounter.yaml
  examples/kubevirt-local-provisioner.yaml
  examples/kubevirt-machinedeployment.yaml
  examples/kubevirt-operator-0.17.4.yaml
  examples/kubevirt-operator-0.19.0.yaml
  pkg/cloudprovider/provider/kubevirt/provider.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
  vendor/k8s.io/utils/LICENSE
  vendor/k8s.io/utils/inotify/LICENSE
  vendor/k8s.io/utils/inotify/PATENTS
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/third_party/forked/golang/PATENTS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle

#606 providerconfig: add omitempty for key in GlobaObjectKeySelector
  pkg/providerconfig/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#609 Add a note about signing-off existing commits to the contributing guidelines
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#611 Simplify the vCenter client creation
  pkg/cloudprovider/provider/vsphere/client.go
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#613 Make the vSphere work with distributed switches
  examples/vsphere-machinedeployment.yaml
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/network.go
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#614 change the name of the kubevirt config
  examples/kubevirt-machinedeployment.yaml
  pkg/cloudprovider/provider/kubevirt/provider.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#615 vSphere: remove CPU limit
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS, team/lifecycle

#618 vSphere: Reconfigure VM's based on the clone's devices, not the template
  pkg/cloudprovider/provider/vsphere/helper.go
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#619 Load required kernel modules based on kernel version
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/coreos/provider.go
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-mirrors.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-proxy.yaml
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-locksmith-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-update-engine-aws.yaml
  pkg/userdata/helper/helper.go
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/template_functions.go
  pkg/userdata/helper/testdata/kublet_systemd_unit_cloud-provider-set.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_multiple-dns-servers.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_pause-image-set.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0.golden
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL, team/lifecycle

#620 vSphere: set VM location
  pkg/cloudprovider/provider/vsphere/helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#621 Fix kernel module loading part 2
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-mirrors.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-proxy.yaml
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-locksmith-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-update-engine-aws.yaml
  pkg/userdata/helper/helper.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#622 Do not create caches for ServiceAccounts and secrets
  Gopkg.lock
  pkg/controller/machine/kubeconfig.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#623 Allow passing arbitrary data onto userdata plugin
  pkg/userdata/manager/plugin.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#624 Set current-context for bootstrap kubeconfig
  pkg/controller/machine/kubeconfig.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#626 remove duplicate import
  pkg/providerconfig/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#627 Add support for Hetzner Private Networks
  Gopkg.lock
  Gopkg.toml
  examples/hetzner-machinedeployment.yaml
  pkg/cloudprovider/provider/hetzner/provider.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/action.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/client.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/datacenter.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/error.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/floating_ip.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/hcloud.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/image.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/iso.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/location.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/network.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/floating_ip.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/location.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/network.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/server.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/schema/volume.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/server.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/server_type.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/ssh_key.go
  vendor/github.com/hetznercloud/hcloud-go/hcloud/volume.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/lifecycle

#628 aws - omitempty for cloudProviderSpec attributes
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle
