Repository kubermatic/machine-controller, pull requests merged in 2019-04, with the labels that each got.

#475 add Linode to README.md
  README.md
Labels: approved, lgtm, needs-ok-to-test, release-note-none, size/XS

#474 Allow using a serviceAccount token instead of bootstrap tokens
  cmd/controller/main.go
  pkg/controller/machine/kubeconfig.go
  pkg/controller/machine/machine.go
Labels: approved, lgtm, release-note-none, size/L

#483 Fix openstack images and add documentation
  README.md
  docs/e2e-infra.md
  docs/openstack-images.md
  docs/operating-system.md
  hack/e2e-setup-openstack-images.sh
  hack/setup-openstack-images.sh
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-openstack-upgrade.yml
Labels: approved, lgtm, release-note-none, size/L

#484 Dont drain during e2e tests
  test/e2e/provisioning/verify.go
Labels: approved, lgtm, release-note-none, size/XS

#485 Use nbg1 as region for Hetzner Cloud instances during e2e tests
  test/e2e/provisioning/testdata/machinedeployment-hetzner.yaml
  test/tools/integration/hetzner.tf
Labels: approved, lgtm, release-note-none, size/XS

#486 Reduce e2e control plane size
  test/tools/integration/hetzner.tf
Labels: approved, lgtm, release-note-none, size/XS

#488 Re-Check on joinClusterTimeout candidates
  hack/ci-e2e-test.sh
  pkg/controller/machine/machine.go
  pkg/controller/machine/machine_test.go
Labels: approved, lgtm, release-note-none, size/M

#477 Update cluster-api to add selective downscaling
  Gopkg.lock
  Gopkg.toml
  pkg/apis/cluster/v1alpha1/conversions/conversions.go
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/aws.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/azure.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/digitalocean.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/hetzner.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/linode.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/openstack.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/vsphere-static-ip.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/vsphere.yaml
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/common/consts.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/delete_policy.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/machine.go
Labels: approved, lgtm, release-note-none, size/L

#480 use automatic detection of the OpenStack BS version
  pkg/cloudprovider/provider/openstack/cloudconfig.go
  pkg/cloudprovider/provider/openstack/cloudconfig_test.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/testdata/bs-defaulting-config.golden
Labels: approved, lgtm, release-note, size/M

#478 Test Kubernetes 1.14
  test/e2e/provisioning/helper.go
  test/tools/integration/provision_master.sh
Labels: approved, lgtm, release-note-none, size/S

#489 Fix go vet for go 1.12
  Makefile
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
Labels: approved, lgtm, release-note-none, size/S

#473 Add UserData plugins
  .gitignore
  Dockerfile
  Makefile
  cmd/userdata/centos/main.go
  cmd/userdata/coreos/main.go
  cmd/userdata/ubuntu/main.go
  cmd/webhook/main.go
  hack/ci-e2e-test.sh
  pkg/admission/admission.go
  pkg/admission/machines.go
  pkg/apis/plugin/plugin.go
  pkg/controller/machine/machine.go
  pkg/userdata/centos/centos.go
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/provider_test.go
  pkg/userdata/convert/ignition-converter.go
  pkg/userdata/coreos/coreos.go
  pkg/userdata/coreos/provider.go
  pkg/userdata/coreos/provider_test.go
  pkg/userdata/manager/manager.go
  pkg/userdata/manager/plugin.go
  pkg/userdata/plugin/plugin.go
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/provider_test.go
  pkg/userdata/ubuntu/ubuntu.go
  pkg/userdata/userdata.go
  test/tools/integration/provision_master.sh
Labels: approved, lgtm, release-note, size/XXL

#487 Preemptible flag for GCE
  examples/gce-machinedeployment.yaml
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/provider.go
Labels: approved, lgtm, release-note, size/S

#476 Enable `CPUAccounting` and `MemoryAccounting` for kubelet.service
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.golden
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.golden
Labels: approved, lgtm, release-note-none, size/M

#492 Dont show leader election log by default
  cmd/controller/main.go
  examples/machine-controller.yaml
  pkg/admission/admission.go
  pkg/admission/machines.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/controller/machine/machine.go
  pkg/node/eviction/eviction.go
Labels: approved, lgtm, release-note-none, size/M

#495 Add team/lifecycle label to all PRs
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS, team/lifecycle

#494 Add CPU and memory accounting cgroup settings for CoreOS and Ubuntu
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.golden
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.golden
  pkg/userdata/coreos/provider.go
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.golden
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.golden
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.golden
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.golden
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.golden
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.golden
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/testdata/kublet_systemd_unit_cloud-provider-set.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_multiple-dns-servers.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0.golden
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
  pkg/userdata/ubuntu/testdata/openstack.golden
  pkg/userdata/ubuntu/testdata/version-1.10.10.golden
  pkg/userdata/ubuntu/testdata/version-1.11.3.golden
  pkg/userdata/ubuntu/testdata/version-1.12.1.golden
  pkg/userdata/ubuntu/testdata/version-1.9.10.golden
  pkg/userdata/ubuntu/testdata/vsphere.golden
Labels: approved, lgtm, release-note-none, size/L, team/lifecycle

#497 add validation for ssh keys
  pkg/admission/machines.go
  pkg/admission/machines_test.go
Labels: approved, lgtm, release-note, size/M, team/lifecycle

#500 Reserve resources for system & kubelet
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.golden
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.golden
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.golden
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.golden
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.golden
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.golden
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.golden
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.golden
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/testdata/kublet_systemd_unit_cloud-provider-set.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_multiple-dns-servers.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0.golden
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
  pkg/userdata/ubuntu/testdata/openstack.golden
  pkg/userdata/ubuntu/testdata/version-1.10.10.golden
  pkg/userdata/ubuntu/testdata/version-1.11.3.golden
  pkg/userdata/ubuntu/testdata/version-1.12.1.golden
  pkg/userdata/ubuntu/testdata/version-1.9.10.golden
  pkg/userdata/ubuntu/testdata/vsphere.golden
Labels: approved, lgtm, release-note, size/L, team/lifecycle

#501 Be more verbose when e2e tests time out waiting for a Node
  test/e2e/provisioning/verify.go
Labels: approved, lgtm, release-note-none, size/M, team/lifecycle

#502 Use ctrlruntime client for e2e test
  .golangci.yml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/deploymentscenario.go
  test/e2e/provisioning/verify.go
Labels: approved, lgtm, release-note-none, size/L, team/lifecycle

#503 Re-check after instance creation
  pkg/controller/machine/machine.go
Labels: approved, lgtm, release-note-none, size/XS, team/lifecycle

#504 Add swapoff to centos so kubelet starts
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.golden
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.golden
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
  pkg/userdata/ubuntu/testdata/openstack.golden
  pkg/userdata/ubuntu/testdata/version-1.10.10.golden
  pkg/userdata/ubuntu/testdata/version-1.11.3.golden
  pkg/userdata/ubuntu/testdata/version-1.12.1.golden
  pkg/userdata/ubuntu/testdata/version-1.9.10.golden
  pkg/userdata/ubuntu/testdata/vsphere.golden
Labels: approved, lgtm, ok-to-test, release-note, size/M, team/lifecycle

#505 Use ctrlruntimeclient for migrations
  .golangci.yml
  Gopkg.lock
  cmd/controller/main.go
  pkg/apis/cluster/v1alpha1/migrations/migrations.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/addtoscheme_cluster_v1alpha1.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/apis.go
Labels: approved, lgtm, release-note-none, size/L, team/lifecycle

#506 Use trust-device-path for Openstack config
  pkg/cloudprovider/provider/openstack/provider.go
Labels: approved, lgtm, release-note-none, size/XS, team/lifecycle

#493 Packet provider
  Gopkg.lock
  Gopkg.toml
  examples/packet-machinedeployment.yaml
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/provider/packet/provider.go
  pkg/providerconfig/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/migrateuidscenario.go
  test/e2e/provisioning/testdata/machinedeployment-packet.yaml
  vendor/github.com/packethost/packngo/LICENSE.txt
  vendor/github.com/packethost/packngo/batches.go
  vendor/github.com/packethost/packngo/bgp_configs.go
  vendor/github.com/packethost/packngo/bgp_sessions.go
  vendor/github.com/packethost/packngo/billing_address.go
  vendor/github.com/packethost/packngo/capacities.go
  vendor/github.com/packethost/packngo/connect.go
  vendor/github.com/packethost/packngo/devices.go
  vendor/github.com/packethost/packngo/email.go
  vendor/github.com/packethost/packngo/events.go
  vendor/github.com/packethost/packngo/facilities.go
  vendor/github.com/packethost/packngo/hardware_reservations.go
  vendor/github.com/packethost/packngo/ip.go
  vendor/github.com/packethost/packngo/notifications.go
  vendor/github.com/packethost/packngo/operatingsystems.go
  vendor/github.com/packethost/packngo/organizations.go
  vendor/github.com/packethost/packngo/packngo.go
  vendor/github.com/packethost/packngo/payment_methods.go
  vendor/github.com/packethost/packngo/plans.go
  vendor/github.com/packethost/packngo/ports.go
  vendor/github.com/packethost/packngo/projects.go
  vendor/github.com/packethost/packngo/rate.go
  vendor/github.com/packethost/packngo/spotmarket.go
  vendor/github.com/packethost/packngo/spotmarketrequest.go
  vendor/github.com/packethost/packngo/sshkeys.go
  vendor/github.com/packethost/packngo/timestamp.go
  vendor/github.com/packethost/packngo/two_factor_auth.go
  vendor/github.com/packethost/packngo/user.go
  vendor/github.com/packethost/packngo/utils.go
  vendor/github.com/packethost/packngo/virtualnetworks.go
  vendor/github.com/packethost/packngo/volumes.go
  vendor/github.com/packethost/packngo/vpn.go
Labels: approved, lgtm, ok-to-test, release-note, size/XXL, team/lifecycle

#507 Make CloudProviderSpec public so that it can be exported
  pkg/cloudprovider/provider/gce/config.go
Labels: approved, lgtm, release-note-none, size/S, team/lifecycle

#509 Fixup header boilerplate
  cmd/userdata/centos/main.go
  cmd/userdata/coreos/main.go
  cmd/userdata/ubuntu/main.go
  hack/e2e-setup-openstack-images.sh
  hack/setup-openstack-images.sh
  pkg/admission/machines_test.go
  pkg/apis/plugin/plugin.go
  pkg/cloudprovider/provider/packet/provider.go
  pkg/userdata/centos/centos.go
  pkg/userdata/coreos/coreos.go
  pkg/userdata/manager/manager.go
  pkg/userdata/manager/plugin.go
  pkg/userdata/plugin/plugin.go
  pkg/userdata/ubuntu/ubuntu.go
Labels: approved, lgtm, release-note-none, size/L, team/lifecycle

#508 add timeout for node eviction to skip evictions which won't succeed
  cmd/controller/main.go
  pkg/controller/machine/machine.go
  pkg/controller/machine/machine_test.go
Labels: approved, lgtm, release-note, size/L, team/lifecycle

#510 Allow creating GCP instances without public address
  examples/gce-machinedeployment.yaml
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/service.go
  test/e2e/provisioning/testdata/machinedeployment-gce.yaml
Labels: approved, lgtm, release-note-none, size/M, team/lifecycle

#511 gce: allow specifying tags for instances
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/provider.go
Labels: approved, lgtm, release-note-none, size/XS, team/lifecycle
