Repository kubermatic/machine-controller, pull requests merged in 2019-03, with the labels that each got.

#466 e2e tests: respect local KUBECONFIG env before using hardcoded path
  README.md
  test/e2e/provisioning/helper.go
Labels: approved, lgtm, release-note-none, size/S

#467 expand openstack cloud config
  .golangci.yml
  pkg/cloudprovider/provider/openstack/cloudconfig.go
  pkg/cloudprovider/provider/openstack/cloudconfig_test.go
  pkg/cloudprovider/provider/openstack/testdata/config-with-special-chars.golden
  pkg/cloudprovider/provider/openstack/testdata/simple-config.golden
  pkg/ini/duration.go
  pkg/ini/escape.go
Labels: approved, lgtm, release-note-none, size/M

#468 Add how-to for adding a new cloud provider
  docs/howto-provider.md
Labels: approved, lgtm, release-note-none, size/M

#470 --cloud-provider=external
  cmd/controller/main.go
  pkg/controller/machine/machine.go
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.golden
  pkg/userdata/centos/userdata.go
  pkg/userdata/centos/userdata_test.go
  pkg/userdata/convert/ignition-converter.go
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.golden
  pkg/userdata/coreos/userdata.go
  pkg/userdata/coreos/userdata_test.go
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/kubelet_test.go
  pkg/userdata/helper/template_functions.go
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0-external.golden
  pkg/userdata/ubuntu/userdata.go
  pkg/userdata/ubuntu/userdata_test.go
  pkg/userdata/userdata.go
Labels: approved, lgtm, release-note, size/XL

#471 Increase inotify limit
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.golden
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.golden
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.golden
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.golden
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.golden
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.golden
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.golden
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.golden
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.golden
  pkg/userdata/helper/helper.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.golden
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.golden
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.golden
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.golden
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.golden
  pkg/userdata/ubuntu/testdata/openstack.golden
  pkg/userdata/ubuntu/testdata/version-1.10.10.golden
  pkg/userdata/ubuntu/testdata/version-1.11.3.golden
  pkg/userdata/ubuntu/testdata/version-1.12.1.golden
  pkg/userdata/ubuntu/testdata/version-1.9.10.golden
  pkg/userdata/ubuntu/testdata/vsphere.golden
  test/tools/integration/provision_master.sh
Labels: approved, lgtm, release-note, size/S

#472 Support for network configuration of GCE instances
  examples/gce-machinedeployment.yaml
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/service.go
Labels: approved, lgtm, release-note, size/M
