Repository kubermatic/machine-controller, pull requests merged in 2019-05, with the labels that each got.

#514 Fix typo in error message
  pkg/providerconfig/types.go
Labels: approved, lgtm, release-note-none, size/XS, team/lifecycle, ¯\_(ツ)_/¯

#513 Preparation for yamllint integration in infra
  .yamllint.conf
  examples/kubevirt-0.10.0.yaml
  examples/packet-machinedeployment.yaml
  pkg/apis/cluster/v1alpha1/conversions/providerconfig_to_providerspec_test.go
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machineDeploymentWithProviderConfig/hetzner.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machineSetWithProviderConfig/hetzner.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machineWithProviderConfig/aws.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machineWithProviderConfig/hetzner.yaml
  pkg/cloudprovider/provider/aws/cloudconfig_test.go
  pkg/cloudprovider/provider/openstack/cloudconfig_test.go
  pkg/cloudprovider/provider/vsphere/cloudconfig_test.go
  pkg/test/helper.go
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/provider_test.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/coreos/provider.go
  pkg/userdata/coreos/provider_test.go
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
  pkg/userdata/helper/common_test.go
  pkg/userdata/helper/download_binaries_script_test.go
  pkg/userdata/helper/kubelet_test.go
  pkg/userdata/helper/template_functions.go
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/provider_test.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
  test/e2e/provisioning/testdata/machinedeployment-packet.yaml
Labels: approved, lgtm, release-note-none, size/XL, team/lifecycle

#515 Create an event and error log for all reconciliaton errors
  pkg/controller/machine/machine.go
Labels: approved, lgtm, release-note-none, size/S, team/lifecycle

#516 Simplify updateMachine and fix finalizer handling
  pkg/controller/machine/machine.go
Labels: approved, lgtm, release-note-none, size/M, team/lifecycle

#522 Make CloudConfig for GCE public
  pkg/cloudprovider/provider/gce/cloudconfig.go
  pkg/cloudprovider/provider/gce/cloudconfig_test.go
  pkg/cloudprovider/provider/gce/provider.go
Labels: approved, lgtm, release-note-none, size/S, team/lifecycle

#525 Fix aws filters to include productCode for CentOS
  Gopkg.lock
  Gopkg.toml
  pkg/cloudprovider/provider/aws/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/dep_service_ids.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/iam/api.go
  vendor/github.com/aws/aws-sdk-go/service/iam/waiters.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/github.com/aws/aws-sdk-go/service/sts/doc.go
  vendor/github.com/aws/aws-sdk-go/service/sts/errors.go
Labels: approved, lgtm, release-note, size/XXL, team/lifecycle

#521 Add machine delete finalizer only after successful creation
  pkg/controller/machine/machine.go
Labels: approved, lgtm, release-note-none, size/XS, team/lifecycle

#523 Allow to specify projectID using PACKET_PROJECT_ID
  pkg/cloudprovider/provider/packet/provider.go
Labels: approved, lgtm, release-note-none, size/XS, team/lifecycle

#526 vSphere VM cleanup after ISO failure
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: approved, lgtm, release-note-none, size/XS, team/lifecycle

#524 Fix check-dependencies to use dep check
  Makefile
Labels: approved, lgtm, release-note-none, size/XS, team/lifecycle

#518 Re-Activate vsphere tests
  hack/ci-e2e-test.sh
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/controller/machine/machine.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: approved, lgtm, release-note-none, size/L, team/lifecycle

#528 Expand CloudConfig for GCE
  pkg/cloudprovider/provider/gce/cloudconfig.go
  pkg/cloudprovider/provider/gce/cloudconfig_test.go
Labels: approved, lgtm, release-note-none, size/S, team/lifecycle

#517 Make vsphere root disk size extendable
  docs/vsphere.md
  examples/vsphere-machinedeployment.yaml
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: approved, lgtm, release-note, size/L, team/lifecycle

#529 Add NetworkName and SubnetworkName to GCP cloudconfig
  pkg/cloudprovider/provider/gce/cloudconfig.go
  pkg/cloudprovider/provider/gce/cloudconfig_test.go
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/provider.go
Labels: approved, lgtm, release-note-none, size/M, team/lifecycle

#530 Add TokenURL in GCE CloudConfig
  pkg/cloudprovider/provider/gce/cloudconfig.go
  pkg/cloudprovider/provider/gce/cloudconfig_test.go
Labels: approved, lgtm, release-note-none, size/XS, team/lifecycle

#527 Rename cloud package to types
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/packet/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/types/types.go
  pkg/cloudprovider/validationwrapper.go
  pkg/controller/machine/machine.go
  test/e2e/provisioning/migrateuidscenario.go
Labels: approved, lgtm, release-note-none, size/L, team/lifecycle

#532 Openstack validation: Force passing in image and flavor
  pkg/cloudprovider/provider/openstack/provider.go
Labels: approved, lgtm, release-note-none, size/XS, team/lifecycle

#533 GCE public IP by default
  pkg/cloudprovider/provider/gce/config.go
Labels: approved, lgtm, release-note, size/S, team/lifecycle

#534 Remove unused `os` field from the packet spec
  pkg/cloudprovider/provider/packet/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#535 Make nikhita and frank maintainers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#537 added > to access key ID field
  examples/aws-machinedeployment.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#539 add DiskIops for AWS provider
  examples/aws-machinedeployment.yaml
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#550 Fix OS docs
  docs/operating-system.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#547 Extend cloudproviderinterface to accept providerData on GET
  .golangci.yml
  cmd/controller/main.go
  pkg/apis/cluster/v1alpha1/migrations/migrations.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/packet/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/types/types.go
  pkg/cloudprovider/validationwrapper.go
  pkg/controller/machine/machine.go
  test/e2e/provisioning/migrateuidscenario.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#551 Azure: start reading credentials from ENV
  examples/azure-machinedeployment.yaml
  pkg/cloudprovider/provider/azure/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S, team/lifecycle
