Repository kubermatic/machine-controller, pull requests merged in 2019-11, with the labels that each got.

#647 Restrict file system permissions for config files
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#649 Stop trying to match Machine{Deployment,Set} to a cluster
  pkg/controller/machinedeployment/machinedeployment_controller.go
  pkg/controller/machineset/machineset_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#648 Vsphere: Power on VMs that are not powered on
  Gopkg.lock
  pkg/cloudprovider/provider/vsphere/provider.go
  vendor/github.com/vmware/govmomi/CONTRIBUTORS
  vendor/github.com/vmware/govmomi/client.go
  vendor/github.com/vmware/govmomi/find/finder.go
  vendor/github.com/vmware/govmomi/govc/test/license.bats
  vendor/github.com/vmware/govmomi/nfc/lease.go
  vendor/github.com/vmware/govmomi/nfc/lease_updater.go
  vendor/github.com/vmware/govmomi/object/cluster_compute_resource.go
  vendor/github.com/vmware/govmomi/object/common.go
  vendor/github.com/vmware/govmomi/object/datastore.go
  vendor/github.com/vmware/govmomi/object/datastore_file.go
  vendor/github.com/vmware/govmomi/object/datastore_path.go
  vendor/github.com/vmware/govmomi/object/diagnostic_manager.go
  vendor/github.com/vmware/govmomi/object/distributed_virtual_portgroup.go
  vendor/github.com/vmware/govmomi/object/file_manager.go
  vendor/github.com/vmware/govmomi/object/host_certificate_manager.go
  vendor/github.com/vmware/govmomi/object/host_datastore_system.go
  vendor/github.com/vmware/govmomi/object/host_network_system.go
  vendor/github.com/vmware/govmomi/object/host_storage_system.go
  vendor/github.com/vmware/govmomi/object/task.go
  vendor/github.com/vmware/govmomi/object/virtual_device_list.go
  vendor/github.com/vmware/govmomi/object/virtual_disk_manager.go
  vendor/github.com/vmware/govmomi/object/virtual_machine.go
  vendor/github.com/vmware/govmomi/property/collector.go
  vendor/github.com/vmware/govmomi/property/filter.go
  vendor/github.com/vmware/govmomi/property/wait.go
  vendor/github.com/vmware/govmomi/session/keep_alive.go
  vendor/github.com/vmware/govmomi/session/manager.go
  vendor/github.com/vmware/govmomi/task/wait.go
  vendor/github.com/vmware/govmomi/vim25/client.go
  vendor/github.com/vmware/govmomi/vim25/methods/methods.go
  vendor/github.com/vmware/govmomi/vim25/methods/service_content.go
  vendor/github.com/vmware/govmomi/vim25/mo/mo.go
  vendor/github.com/vmware/govmomi/vim25/mo/retrieve.go
  vendor/github.com/vmware/govmomi/vim25/mo/type_info.go
  vendor/github.com/vmware/govmomi/vim25/progress/reader.go
  vendor/github.com/vmware/govmomi/vim25/soap/client.go
  vendor/github.com/vmware/govmomi/vim25/soap/debug.go
  vendor/github.com/vmware/govmomi/vim25/soap/error.go
  vendor/github.com/vmware/govmomi/vim25/soap/soap.go
  vendor/github.com/vmware/govmomi/vim25/types/enum.go
  vendor/github.com/vmware/govmomi/vim25/types/helpers.go
  vendor/github.com/vmware/govmomi/vim25/types/if.go
  vendor/github.com/vmware/govmomi/vim25/types/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle

#650 vSphere: Remove tag-based handling for multiple machines with the same name
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#651 vSphere: Use absolute path when trying to find vms
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#652 Update the kubernetes versions for e2e tests
  examples/machine-controller.yaml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/tools/integration/provision_master.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#654 Fix the cleanup condition in azure cloud provider
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/util/util.go
  pkg/cloudprovider/util/util_test.go
  test/e2e/provisioning/migrateuidscenario.go
  test/e2e/provisioning/verify.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#657 say "machine controller has been successfully stopped" on shutdown, not startup
  cmd/controller/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#656 Add coreos support to kubevirt
  pkg/cloudprovider/provider/kubevirt/provider.go
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle
