Repository kubermatic/machine-controller, pull requests merged in 2019-12, with the labels that each got.

#658 Add support for Kubernetes 1.17 on CoreOS
  pkg/userdata/coreos/provider.go
  pkg/userdata/coreos/provider_test.go
  pkg/userdata/coreos/testdata/v1.17.0.yaml
  test/e2e/provisioning/helper.go
  test/tools/integration/provision_master.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#660 Documenting the coreos image which is used in Kubevirt cloud provider
  docs/kubevirt.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#662 use subtests in some table-tests to spot failures easier
  pkg/clusterinfo/configmap_test.go
  pkg/userdata/centos/provider_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#661 set a dynamic config snapshot directory
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-mirrors.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-proxy.yaml
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/coreos/testdata/v1.17.0.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-locksmith-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-update-engine-aws.yaml
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/testdata/kublet_systemd_unit_cloud-provider-set.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_multiple-dns-servers.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_pause-image-set.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0.golden
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#659 Add suse linux enterprise server as an os option
  .prow.yaml
  Makefile
  cmd/userdata/sles/main.go
  examples/aws-machinedeployment.yaml
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/machines/v1alpha1/machines_client.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/machines/v1alpha1/zz_generated.deepcopy.go
  pkg/providerconfig/types/types.go
  pkg/userdata/manager/manager.go
  pkg/userdata/sles/provider.go
  pkg/userdata/sles/provider_test.go
  pkg/userdata/sles/sles.go
  pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/sles/testdata/multiple-dns-servers.yaml
  pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
  pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/sles/testdata/openstack.yaml
  pkg/userdata/sles/testdata/version-1.10.10.yaml
  pkg/userdata/sles/testdata/version-1.11.3.yaml
  pkg/userdata/sles/testdata/version-1.12.1.yaml
  pkg/userdata/sles/testdata/version-1.9.10.yaml
  pkg/userdata/sles/testdata/vsphere-mirrors.yaml
  pkg/userdata/sles/testdata/vsphere-proxy.yaml
  pkg/userdata/sles/testdata/vsphere.yaml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-aws.yaml
  test/tools/integration/provision_master.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle
