Repository kubermatic/machine-controller, pull requests merged in 2019-07, with the labels that each got.

#583 Always add instance delete finalizer initially
  pkg/controller/machine/machine.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#580 Add Openstack tenant id
  pkg/cloudprovider/provider/openstack/cloudconfig.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/testdata/bs-defaulting-config.golden
  pkg/cloudprovider/provider/openstack/testdata/config-with-special-chars.golden
  pkg/cloudprovider/provider/openstack/testdata/simple-config.golden
  pkg/providerconfig/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#584 Make Openstack NodeVolumeAttachLimit configurable
  pkg/cloudprovider/provider/openstack/cloudconfig.go
  pkg/cloudprovider/provider/openstack/cloudconfig_test.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/testdata/config-with-special-chars.golden
  pkg/cloudprovider/provider/openstack/testdata/simple-config.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#589 Ubuntu: Disable ufw
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: no, lgtm, release-note-none, size/S, team/lifecycle

#588 Run Docker with systemd cgroup driver
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-mirrors.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-proxy.yaml
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-locksmith-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-update-engine-aws.yaml
  pkg/userdata/helper/helper.go
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/testdata/kublet_systemd_unit_cloud-provider-set.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_multiple-dns-servers.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_pause-image-set.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.10.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.11.3.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.12.0.golden
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#590 Azure: Assign security group to instances
  examples/azure-machinedeployment.yaml
  pkg/cloudprovider/provider/azure/create_delete_resources.go
Labels: approved, dco-signoff: no, lgtm, release-note-none, size/M, team/lifecycle

#582 Use dynamic client everywhere
  Gopkg.lock
  cmd/controller/main.go
  cmd/webhook/main.go
  examples/machine-controller.yaml
  pkg/admission/admission.go
  pkg/admission/machines.go
  pkg/apis/cluster/v1alpha1/migrations/migrations.go
  pkg/controller/machine/kubeconfig.go
  pkg/controller/machine/kubeconfig_test.go
  pkg/controller/machine/machine.go
  pkg/controller/machine/machine_test.go
  pkg/controller/machine/metrics.go
  pkg/node/eviction/eviction.go
  pkg/node/eviction/eviction_test.go
  pkg/providerconfig/types.go
  test/e2e/provisioning/migrateuidscenario.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/fake/register.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/doc.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_cluster.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_cluster_client.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_machine.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_machineclass.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_machinedeployment.go
  vendor/sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake/fake_machineset.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: approved, lgtm, release-note-none, size/XXL, team/lifecycle

#591 Fix typo in the GlobalObjectKeySelector type name
  pkg/providerconfig/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#593 Fix typo in error message
  pkg/controller/machine/machine.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#594 Aws optional public ip
  examples/aws-machinedeployment.yaml
  pkg/cloudprovider/provider/aws/provider.go
  test/e2e/provisioning/testdata/machinedeployment-aws.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#603 [release/v1.4] Correctly return sync errors
  pkg/controller/machine/machine.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle
