Repository kubermatic/machine-controller, pull requests merged in 2020-09, with the labels that each got.

#815 Update Docker to 19.03.12 for Ubuntu, CentOS, RHEL
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/helper/helper.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.17.3.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#816 Ignore Node when deleting by NodeRef if it doesn't exist anymore
  pkg/controller/machine/machine.go
  pkg/controller/machine/machine_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#817 new hetzner field "image"
  examples/hetzner-machinedeployment.yaml
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/hetzner/types/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#818 Update CNI plugins to v0.8.7
  pkg/userdata/centos/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/coreos/testdata/v1.16.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.17.0-vsphere-mirrors.yaml
  pkg/userdata/coreos/testdata/v1.17.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.17.0-vsphere-proxy.yaml
  pkg/userdata/coreos/testdata/v1.17.0.yaml
  pkg/userdata/coreos/testdata/v1.17.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.17.2-disable-auto-update-aws.yaml
  pkg/userdata/coreos/testdata/v1.17.2-disable-locksmith-aws.yaml
  pkg/userdata/coreos/testdata/v1.17.2-disable-update-engine-aws.yaml
  pkg/userdata/coreos/testdata/v1.17.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/flatcar/testdata/v1.17.0.yaml
  pkg/userdata/flatcar/testdata/v1.18.0.yaml
  pkg/userdata/helper/download_binaries_script.go
  pkg/userdata/helper/testdata/download_binaries_v1.10.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.3.golden
  pkg/userdata/helper/testdata/download_binaries_v1.12.0.golden
  pkg/userdata/helper/testdata/safe_download_binaries_v1.18.2.golden
  pkg/userdata/rhel/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/sles/testdata/multiple-dns-servers.yaml
  pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
  pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/sles/testdata/openstack.yaml
  pkg/userdata/sles/testdata/version-1.15.10.yaml
  pkg/userdata/sles/testdata/version-1.16.3.yaml
  pkg/userdata/sles/testdata/version-1.17.1.yaml
  pkg/userdata/sles/testdata/vsphere-mirrors.yaml
  pkg/userdata/sles/testdata/vsphere-proxy.yaml
  pkg/userdata/sles/testdata/vsphere.yaml
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.15.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.16.6.yaml
  pkg/userdata/ubuntu/testdata/version-1.17.3.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#822 Disable CoreOS E2E tests on GCE and DigitalOcean
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#821 Add support for setting arbitrary feature gates on the kubelet
  cmd/machine-controller/main.go
  pkg/apis/plugin/plugin.go
  pkg/controller/machine/machine.go
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/provider_test.go
  pkg/userdata/coreos/provider.go
  pkg/userdata/coreos/provider_test.go
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/provider_test.go
  pkg/userdata/helper/kubelet.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/provider_test.go
  pkg/userdata/sles/provider.go
  pkg/userdata/sles/provider_test.go
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/provider_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#826 Fix releasever to 7 for RHEL and CentOS in yum docker repository
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S, team/lifecycle

#824 Fix hanging reboot on auto update.
  pkg/userdata/flatcar/provider.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S, team/lifecycle

#828 [v1.14] Fix releasever to 7 for RHEL and CentOS in yum docker repository (#826)
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt-dns-config.yaml
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle
