Repository kubermatic/machine-controller, pull requests merged in 2020-04, with the labels that each got.

#729 OS support documentation
  docs/operating-system.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#733 Update the examples folder
  docs/kubevirt.md
  docs/rhel-custom-image.md
  examples/alibaba-machinedeployment.yaml
  examples/aws-machinedeployment.yaml
  examples/azure-machinedeployment.yaml
  examples/gce-machinedeployment.yaml
  examples/openstack-machinedeployment.yaml
  examples/vsphere-datastore-cluster-machinedeployment.yaml
  examples/vsphere-machinedeployment.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#728 Update cloud provider spec documentation
  docs/cloud-provider.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#734 Adjust the rhel documentation to refer to the supported OS file
  docs/rhel-custom-image.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#736 Improve vsphere doc
  docs/cloud-provider.md
  docs/operating-system.md
  docs/rhel-custom-image.md
  docs/vsphere.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#738 adding azure az support
  examples/azure-machinedeployment.yaml
  pkg/cloudprovider/provider/azure/create_delete_resources.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/azure/types/types.go
  test/e2e/provisioning/testdata/machinedeployment-azure.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#726 Add vSphere ResourcePool support
  docs/vsphere.md
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/provider_test.go
  pkg/cloudprovider/provider/vsphere/types/types.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/M, team/lifecycle

#741 Upgrade kubevirt go-client
  go.mod
  go.sum
  pkg/admission/machines.go
  pkg/apis/cluster/v1alpha1/migrations/migrations.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#744 Use addresses instead of node ref for rhel aws instances
  pkg/cloudprovider/instance/instance.go
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/gce/instance.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/packet/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/controller/machine/machine.go
  pkg/controller/machine/machine_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#745 Support flatcar in aws
  Makefile
  cmd/userdata/flatcar/main.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/providerconfig/types/types.go
  pkg/userdata/flatcar/flatcar.go
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/provider_test.go
  pkg/userdata/flatcar/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/flatcar/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/flatcar/testdata/v1.11.2-vsphere-static-ipconfig.yaml
  pkg/userdata/flatcar/testdata/v1.12.0-vsphere-mirrors.yaml
  pkg/userdata/flatcar/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/flatcar/testdata/v1.12.0-vsphere-proxy.yaml
  pkg/userdata/flatcar/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/flatcar/testdata/v1.17.0.yaml
  pkg/userdata/flatcar/testdata/v1.9.2-disable-auto-update-aws-external.yaml
  pkg/userdata/flatcar/testdata/v1.9.2-disable-auto-update-aws.yaml
  pkg/userdata/flatcar/testdata/v1.9.2-disable-locksmith-aws.yaml
  pkg/userdata/flatcar/testdata/v1.9.2-disable-update-engine-aws.yaml
  pkg/userdata/manager/manager.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle

#740 vSphere resource pool test
  .prow.yaml
  pkg/cloudprovider/provider/vsphere/helper_test.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#747 Adding kubevirt dnsconfig
  .prow.yaml
  go.mod
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt-dns-config.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#748 adding support for flatcar in azure
  pkg/cloudprovider/provider/azure/provider.go
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#749 adding openstack test
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#750 Support flatcar in vsphere
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider.go
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle
