Repository kubermatic/machine-controller, pull requests merged in 2020-11, with the labels that each got.

#835 feat: add Scaleway as a provider
  .prow.yaml
  docs/cloud-provider.md
  examples/scaleway-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/cloudprovider/provider/scaleway/types/types.go
  pkg/providerconfig/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-scaleway.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/XL, team/lifecycle

#843 Implement a configurable timeout for OpenStack
  examples/openstack-machinedeployment.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/machinesv1alpha1machine/openstack.yaml
  pkg/apis/cluster/v1alpha1/conversions/testdata/migrated_clusterv1alpha1machine/openstack.yaml
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/provider_test.go
  pkg/cloudprovider/provider/openstack/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-openstack-upgrade.yml
  test/e2e/provisioning/testdata/machinedeployment-openstack.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-action-required, size/M, team/lifecycle

#842 Add Anexia cloud provider
  .prow.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/provider/anexia/instance.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-anexia.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/lifecycle

#845 add very short document about anexia stating that this is an alpha cl…
  docs/anexia.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS, team/lifecycle

#847 upgrade terraform to 0.13.5
  test/tools/integration/Makefile
  test/tools/integration/versions.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#846 Refactor the KubeVirt dns settings
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/types/types.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt-dns-config.yaml
Labels: approved, dco-signoff: yes, lgtm, priority/high, release-note, size/S, team/lifecycle

#848 fix openstack instanceReadyPeriod/Timeout
  pkg/cloudprovider/provider/openstack/provider.go
  test/e2e/provisioning/testdata/machinedeployment-openstack-upgrade.yml
  test/e2e/provisioning/testdata/machinedeployment-openstack.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle
