Repository kubermatic/machine-controller, pull requests merged in 2020-01, with the labels that each got.

#664 kubelet sets intial machine taints via --register-with-taints
  pkg/userdata/centos/provider.go
  pkg/userdata/coreos/provider.go
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/kubelet_test.go
  pkg/userdata/helper/testdata/kublet_systemd_unit_taints-set.golden
  pkg/userdata/sles/provider.go
  pkg/userdata/ubuntu/provider.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L, team/lifecycle

#665 Add machine controller kubeconfig env variable
  hack/run-machine-controller.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#669 Support RedHat Enterprise Linux os in the machine controller
  Makefile
  cmd/userdata/rhel/main.go
  examples/kubevirt-machinedeployment.yaml
  examples/vsphere-machinedeployment.yaml
  hack/ci-e2e-test.sh
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/providerconfig/types/types.go
  pkg/userdata/manager/manager.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/provider_test.go
  pkg/userdata/rhel/rhel.go
  pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle

#666 Enable swap accounting for ubuntu deployments
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle
