Repository kubermatic/machine-controller, pull requests merged in 2020-03, with the labels that each got.

#703 add rhel support to the gcp cloud provider
  .prow.yaml
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/gce/types/cloudconfig.go
  pkg/cloudprovider/provider/gce/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-gce.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#698 Add support for configurable Azure disk sizes
  examples/azure-machinedeployment.yaml
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/azure/types/types.go
  test/e2e/provisioning/testdata/machinedeployment-azure.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#704 Enable subscription manager for aws
  pkg/cloudprovider/provider/aws/provider.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
  test/e2e/provisioning/helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#705 Implement the NodeCSRApprover controller
  cmd/machine-controller/main.go
  pkg/controller/nodecsrapprover/doc.go
  pkg/controller/nodecsrapprover/node_csr_approver.go
  pkg/controller/nodecsrapprover/node_csr_approver_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#706 Enable redhat subscriptions pagination
  pkg/cloudprovider/rhsm/subscription_manager.go
  pkg/cloudprovider/rhsm/subscription_manager_test.go
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#708 Use OAuth2 client instead of implementing access token retrieval and refresh
  pkg/cloudprovider/rhsm/subscription_manager.go
  pkg/cloudprovider/rhsm/subscription_manager_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#707 Add additional validations in NodeCSRApprover controller
  pkg/controller/nodecsrapprover/node_csr_approver.go
  pkg/controller/nodecsrapprover/node_csr_approver_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL, team/lifecycle

#713 fix build script regression from #680
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#715 fix tag build regression from #680
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#712 Converge docker.json config usage across operating systems
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-mirrors.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-proxy.yaml
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/coreos/testdata/v1.17.0.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-locksmith-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-update-engine-aws.yaml
  pkg/userdata/helper/helper.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/sles/testdata/multiple-dns-servers.yaml
  pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
  pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/sles/testdata/openstack.yaml
  pkg/userdata/sles/testdata/version-1.10.10.yaml
  pkg/userdata/sles/testdata/version-1.11.3.yaml
  pkg/userdata/sles/testdata/version-1.12.1.yaml
  pkg/userdata/sles/testdata/version-1.9.10.yaml
  pkg/userdata/sles/testdata/vsphere-mirrors.yaml
  pkg/userdata/sles/testdata/vsphere-proxy.yaml
  pkg/userdata/sles/testdata/vsphere.yaml
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#721 Remove nikhita from OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#710 Fix the ip address updating in the cluster status
  examples/machine-controller.yaml
  hack/ci-e2e-test.sh
  pkg/cloudprovider/provider/azure/get_client.go
  pkg/cloudprovider/provider/azure/provider.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-azure.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#724 Restructure redhat subscription manager
  .prow.yaml
  examples/aws-machinedeployment.yaml
  examples/azure-machinedeployment.yaml
  examples/gce-machinedeployment.yaml
  examples/kubevirt-machinedeployment.yaml
  examples/openstack-machinedeployment.yaml
  examples/vsphere-datastore-cluster-machinedeployment.yaml
  examples/vsphere-machinedeployment.yaml
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/aws/types/types.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/azure/types/types.go
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/gce/types/types.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/types/types.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/types/types.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/types/types.go
  pkg/controller/machine/machine.go
  pkg/rhsm/subscription_manager.go
  pkg/rhsm/subscription_manager_test.go
  pkg/rhsm/util.go
  pkg/userdata/rhel/rhel.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-aws.yaml
  test/e2e/provisioning/testdata/machinedeployment-azure.yaml
  test/e2e/provisioning/testdata/machinedeployment-gce.yaml
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
  test/e2e/provisioning/testdata/machinedeployment-openstack.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#725 disable rhel e2e tests except for kubevirt
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle
