Repository kubermatic/machine-controller, pull requests merged in 2020-10, with the labels that each got.

#830 Fix polkit rules filename for flatcar reboot.
  pkg/userdata/flatcar/provider.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/XS, team/lifecycle

#811 Always ensure to have machine-delete-finalizer
  pkg/controller/machine/machine.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S, team/lifecycle

#827 Update e2e tests to run all the currently supported k8s versions
  Makefile
  README.md
  examples/webhook-certificate.cnf
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/tools/integration/Makefile
  test/tools/integration/master_install_script.sh
  test/tools/integration/provision_master.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#841 Add Anexia Cloud Provider Spec to Machine-Controller
  examples/anexia-machinedeployment.yaml
  pkg/cloudprovider/provider/anexia/types/types.go
  pkg/providerconfig/types/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#840 Support cloud-init for flatcar
  .prow.yaml
  cmd/userdata/flatcar/main.go
  pkg/userdata/flatcar/flatcar.go
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/provider_test.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.17.0.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.18.0.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.19.0.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.17.0.json
  pkg/userdata/flatcar/testdata/ignition_v1.18.0.json
  pkg/userdata/flatcar/testdata/ignition_v1.19.0.json
  pkg/userdata/flatcar/testdata/v1.17.0.yaml
  pkg/userdata/flatcar/testdata/v1.18.0.yaml
  pkg/userdata/flatcar/testdata/v1.19.0.yaml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-aws.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle
