Repository kubermatic/machine-controller, pull requests merged in 2020-12, with the labels that each got.

#853 Update to Go 1.15.1
  .prow.yaml
  Dockerfile
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#854 Document kubevirt installation
  docs/kubevirt.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#857 Fix various typos
  cmd/machine-controller/main.go
  docs/cloud-provider.md
  docs/howto-provider.md
  docs/kubevirt.md
  docs/rhel-custom-image.md
  docs/vsphere.md
  examples/kubevirt-machinedeployment.yaml
  examples/machine-controller.yaml
  hack/ci-e2e-test.sh
  image-builder/build.sh
  pkg/apis/cluster/v1alpha1/conversions/providerconfig_to_providerspec_test.go
  pkg/apis/cluster/v1alpha1/migrations/migrations.go
  pkg/cloudprovider/cache/cloudprovidercache_test.go
  pkg/cloudprovider/common/ssh/ssh.go
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/types/types.go
  pkg/controller/machine/machine.go
  pkg/controller/machine/machine_test.go
  pkg/controller/machine/metrics.go
  pkg/machines/v1alpha1/types.go
  pkg/node/eviction/eviction.go
  pkg/rhsm/subscription_manager.go
  pkg/userdata/plugin/plugin.go
  pkg/userdata/scripts/health-monitor.sh
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/verify.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#859 terraform fmt
  test/tools/integration/hetzner.tf
  test/tools/integration/output.tf
  test/tools/integration/versions.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#862 Fix flatcar supprot for packet
  pkg/userdata/centos/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/coreos/testdata/v1.16.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.17.0-vsphere-mirrors.yaml
  pkg/userdata/coreos/testdata/v1.17.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.17.0-vsphere-proxy.yaml
  pkg/userdata/coreos/testdata/v1.17.0.yaml
  pkg/userdata/coreos/testdata/v1.17.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.17.2-disable-auto-update-aws.yaml
  pkg/userdata/coreos/testdata/v1.17.2-disable-locksmith-aws.yaml
  pkg/userdata/coreos/testdata/v1.17.2-disable-update-engine-aws.yaml
  pkg/userdata/coreos/testdata/v1.17.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.17.0.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.18.0.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.19.0.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.17.0.json
  pkg/userdata/flatcar/testdata/ignition_v1.18.0.json
  pkg/userdata/flatcar/testdata/ignition_v1.19.0.json
  pkg/userdata/helper/kubelet.go
  pkg/userdata/rhel/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/sles/testdata/multiple-dns-servers.yaml
  pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
  pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/sles/testdata/openstack.yaml
  pkg/userdata/sles/testdata/version-1.15.10.yaml
  pkg/userdata/sles/testdata/version-1.16.3.yaml
  pkg/userdata/sles/testdata/version-1.17.1.yaml
  pkg/userdata/sles/testdata/vsphere-mirrors.yaml
  pkg/userdata/sles/testdata/vsphere-proxy.yaml
  pkg/userdata/sles/testdata/vsphere.yaml
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.15.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.16.6.yaml
  pkg/userdata/ubuntu/testdata/version-1.17.3.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#860 Remove cloud-init flag from the Anexia provider
  pkg/cloudprovider/provider/anexia/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#866 Retry MachineDeployment creation during tests
  test/e2e/provisioning/verify.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#864 Add gocache and goproxy to CI jobs
  .prow.yaml
  Makefile
  hack/ci-download-gocache.sh
  hack/ci-e2e-test.sh
  hack/ci-upload-gocache.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#858 Update Go Dependencies
  go.mod
  go.sum
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/aws/types/cloudconfig.go
  pkg/cloudprovider/provider/gce/types/cloudconfig.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/openstack/types/cloudconfig.go
  pkg/cloudprovider/provider/vsphere/types/cloudconfig.go
  pkg/ini/escape_test.go
  pkg/userdata/helper/template_functions.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle
