Repository kubermatic/machine-controller, pull requests merged in 2020-07, with the labels that each got.

#790 fixing flatcar ignition support in kubevirt
  go.mod
  go.sum
  pkg/cloudprovider/provider/kubevirt/provider.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt-dns-config.yaml
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S, team/lifecycle

#791 fix json tag for ImagePlan azure
  pkg/cloudprovider/provider/azure/types/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#737 Add spot instance flag to example doc
  docs/cloud-provider.md
  examples/aws-machinedeployment.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#794 adjust the source url for the registry server
  test/e2e/provisioning/testdata/machinedeployment-kubevirt-dns-config.yaml
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#793 Make it work for CentOS7/CentOS8/RHEL7/RHEL8
  .prow.yaml
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#797 Add CSR RBAC to the example manifest
  examples/machine-controller.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#798 Reduce disk storage consumption in Openstack e2e tests
  test/e2e/provisioning/testdata/machinedeployment-openstack-upgrade.yml
  test/e2e/provisioning/testdata/machinedeployment-openstack.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#799 Add proper hostnames to the GCP Machine objects
  pkg/cloudprovider/provider/gce/instance.go
  pkg/cloudprovider/provider/gce/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle
