Repository kubermatic/machine-controller, pull requests merged in 2020-05, with the labels that each got.

#751 Drop some optional packages from installing
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/sles/provider.go
  pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/sles/testdata/multiple-dns-servers.yaml
  pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
  pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/sles/testdata/openstack.yaml
  pkg/userdata/sles/testdata/version-1.10.10.yaml
  pkg/userdata/sles/testdata/version-1.11.3.yaml
  pkg/userdata/sles/testdata/version-1.12.1.yaml
  pkg/userdata/sles/testdata/version-1.9.10.yaml
  pkg/userdata/sles/testdata/vsphere-mirrors.yaml
  pkg/userdata/sles/testdata/vsphere-proxy.yaml
  pkg/userdata/sles/testdata/vsphere.yaml
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#752 add datastore-cluster to GlobalOpts
  pkg/cloudprovider/provider/vsphere/types/cloudconfig.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#754 revert add datastore-cluster to GlobalOpts (#752)
  pkg/cloudprovider/provider/vsphere/types/cloudconfig.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#755 Fix setup script permissions
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#759 Bind docker-ce-cli to the same version as docker-ce
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#763 [release/v1.11] Bind docker-ce-cli to the same version as docker-ce
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#764 [release/v1.8] Bind docker-ce-cli to the same version as docker-ce
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#762 [release/v1.10] Bind docker-ce-cli to the same version as docker-ce
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#766 bump CNI Plugins to v0.8.6
  pkg/userdata/centos/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/coreos/testdata/v1.16.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.17.0-vsphere-mirrors.yaml
  pkg/userdata/coreos/testdata/v1.17.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.17.0-vsphere-proxy.yaml
  pkg/userdata/coreos/testdata/v1.17.0.yaml
  pkg/userdata/coreos/testdata/v1.17.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.17.2-disable-auto-update-aws.yaml
  pkg/userdata/coreos/testdata/v1.17.2-disable-locksmith-aws.yaml
  pkg/userdata/coreos/testdata/v1.17.2-disable-update-engine-aws.yaml
  pkg/userdata/coreos/testdata/v1.17.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/flatcar/testdata/v1.17.0.yaml
  pkg/userdata/helper/download_binaries_script.go
  pkg/userdata/helper/testdata/download_binaries_v1.10.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.3.golden
  pkg/userdata/helper/testdata/download_binaries_v1.12.0.golden
  pkg/userdata/helper/testdata/safe_download_binaries_v1.18.2.golden
  pkg/userdata/rhel/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/sles/testdata/multiple-dns-servers.yaml
  pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
  pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/sles/testdata/openstack.yaml
  pkg/userdata/sles/testdata/version-1.15.10.yaml
  pkg/userdata/sles/testdata/version-1.16.3.yaml
  pkg/userdata/sles/testdata/version-1.17.1.yaml
  pkg/userdata/sles/testdata/vsphere-mirrors.yaml
  pkg/userdata/sles/testdata/vsphere-proxy.yaml
  pkg/userdata/sles/testdata/vsphere.yaml
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.15.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.16.6.yaml
  pkg/userdata/ubuntu/testdata/version-1.17.3.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#769 [release/v1.8] bump CNI Plugins to v0.8.6
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-mirrors.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-proxy.yaml
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/coreos/testdata/v1.17.0.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-locksmith-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-update-engine-aws.yaml
  pkg/userdata/helper/download_binaries_script.go
  pkg/userdata/helper/testdata/download_binaries_v1.10.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.3.golden
  pkg/userdata/helper/testdata/download_binaries_v1.12.0.golden
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#767 [release/v1.11] bump CNI Plugins to v0.8.6
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-mirrors.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-proxy.yaml
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/coreos/testdata/v1.17.0.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-locksmith-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-update-engine-aws.yaml
  pkg/userdata/helper/download_binaries_script.go
  pkg/userdata/helper/testdata/download_binaries_v1.10.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.3.golden
  pkg/userdata/helper/testdata/download_binaries_v1.12.0.golden
  pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/sles/testdata/multiple-dns-servers.yaml
  pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
  pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/sles/testdata/openstack.yaml
  pkg/userdata/sles/testdata/version-1.10.10.yaml
  pkg/userdata/sles/testdata/version-1.11.3.yaml
  pkg/userdata/sles/testdata/version-1.12.1.yaml
  pkg/userdata/sles/testdata/version-1.9.10.yaml
  pkg/userdata/sles/testdata/vsphere-mirrors.yaml
  pkg/userdata/sles/testdata/vsphere-proxy.yaml
  pkg/userdata/sles/testdata/vsphere.yaml
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#768 [release/v1.10] bump CNI Plugins to v0.8.6
  pkg/userdata/centos/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/coreos/testdata/auto-update-openstack-kubelet-v-version-prefix.yaml
  pkg/userdata/coreos/testdata/v1.10.3-auto-update-openstack-multiple-dns.yaml
  pkg/userdata/coreos/testdata/v1.11.2-vsphere-static-ipconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-mirrors.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-overwrite-cloudconfig.yaml
  pkg/userdata/coreos/testdata/v1.12.0-vsphere-proxy.yaml
  pkg/userdata/coreos/testdata/v1.15.0-vsphere.yaml
  pkg/userdata/coreos/testdata/v1.17.0.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws-external.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-auto-update-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-locksmith-aws.yaml
  pkg/userdata/coreos/testdata/v1.9.2-disable-update-engine-aws.yaml
  pkg/userdata/helper/download_binaries_script.go
  pkg/userdata/helper/testdata/download_binaries_v1.10.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0-rc.2.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.0.golden
  pkg/userdata/helper/testdata/download_binaries_v1.11.3.golden
  pkg/userdata/helper/testdata/download_binaries_v1.12.0.golden
  pkg/userdata/rhel/testdata/kubelet-v1.10-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.11-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.12-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.9-aws.yaml
  pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/sles/testdata/multiple-dns-servers.yaml
  pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
  pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/sles/testdata/openstack.yaml
  pkg/userdata/sles/testdata/version-1.10.10.yaml
  pkg/userdata/sles/testdata/version-1.11.3.yaml
  pkg/userdata/sles/testdata/version-1.12.1.yaml
  pkg/userdata/sles/testdata/version-1.9.10.yaml
  pkg/userdata/sles/testdata/vsphere-mirrors.yaml
  pkg/userdata/sles/testdata/vsphere-proxy.yaml
  pkg/userdata/sles/testdata/vsphere.yaml
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.10.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.11.3.yaml
  pkg/userdata/ubuntu/testdata/version-1.12.1.yaml
  pkg/userdata/ubuntu/testdata/version-1.9.10.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#770 [release/v1.8] copy .prow.yaml from infra repo
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#773 Revert "Drop some optional packages from installing (#751)"
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/sles/provider.go
  pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/sles/testdata/multiple-dns-servers.yaml
  pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
  pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/sles/testdata/openstack.yaml
  pkg/userdata/sles/testdata/version-1.15.10.yaml
  pkg/userdata/sles/testdata/version-1.16.3.yaml
  pkg/userdata/sles/testdata/version-1.17.1.yaml
  pkg/userdata/sles/testdata/vsphere-mirrors.yaml
  pkg/userdata/sles/testdata/vsphere-proxy.yaml
  pkg/userdata/sles/testdata/vsphere.yaml
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.15.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.16.6.yaml
  pkg/userdata/ubuntu/testdata/version-1.17.3.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle
