Repository kubermatic/machine-controller, pull requests merged in 2020-06, with the labels that each got.

#775 Defaulting rhel machine to latest rhel 8.x version when no ami is def…
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S, team/lifecycle

#778 Use cloud-init rh_subscription module to register and auto-attach subscriptions
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.15-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.16-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.17-vsphere.yaml
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#784 Disable rhel tests untill subscriptions are renewed
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#782 Assign external IP and DNS name for GCP machines
  pkg/cloudprovider/provider/gce/instance.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS, team/lifecycle

#786 Fix creation of servers with custom disk size on OpenStack
  go.mod
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/provider_test.go
  pkg/cloudprovider/provider/vsphere/provider_test.go
  pkg/cloudprovider/testing/testing.go
  pkg/cloudprovider/util/http.go
  test/e2e/provisioning/testdata/machinedeployment-openstack.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL, team/lifecycle

#789 Add rhel satellite subscription
  .prow.yaml
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/azure/types/types.go
  pkg/controller/machine/machine.go
  pkg/rhsm/satellite_subscription_manager.go
  pkg/rhsm/satellite_subscription_manager_test.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/rhel.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-azure-redhat-satellite.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle
