Repository kubermatic/machine-controller, pull requests merged in 2021-08, with the labels that each got.

#1029 prevent AWS metrics from growing over time
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1027 support flatcar in KubeVirt cloud provider
  pkg/cloudprovider/provider/kubevirt/provider.go
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1030 cleanup persistent spot instances when machine is deleted
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, lgtm, release-note, size/S, dco-signoff: yes

#1041 Disable centos tests for azure cloud provider
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1042 Choose the right centos sku in azure
  pkg/cloudprovider/provider/azure/provider.go
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes

#1038 Upgrade CRDs to apiextensions/v1
  examples/cdi-operator.yaml
  examples/kubevirt-operator-0.19.0.yaml
  examples/machine-controller.yaml
Labels: approved, lgtm, release-note, size/XXL, dco-signoff: yes

#1045 Refactor KubeVirt options parser and add KubeVirt cloud config
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/types/cloudconfig.go
  pkg/providerconfig/types/types.go
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes
