Repository kubermatic/machine-controller, pull requests merged in 2021-05, with the labels that each got.

#957 Flatcar version in AWS fix
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#961 E2E test for flatcar with containerd in AWS
  .prow.yaml
  test/e2e/provisioning/all_e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#962 organize import statements
  .gimps.yaml
  cmd/machine-controller/main.go
  cmd/userdata/centos/main.go
  cmd/userdata/flatcar/main.go
  cmd/userdata/rhel/main.go
  cmd/userdata/sles/main.go
  cmd/userdata/ubuntu/main.go
  pkg/admission/admission.go
  pkg/admission/machinedeployments_validation.go
  pkg/apis/cluster/common/plugins.go
  pkg/apis/cluster/v1alpha1/conversions/providerconfig_to_providerspec_test.go
  pkg/cloudprovider/common/ssh/ssh.go
  pkg/cloudprovider/provider/aws/types/cloudconfig.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/gce/service.go
  pkg/cloudprovider/provider/gce/types/cloudconfig.go
  pkg/cloudprovider/provider/openstack/provider_test.go
  pkg/cloudprovider/provider/openstack/types/cloudconfig.go
  pkg/cloudprovider/provider/openstack/types/cloudconfig_test.go
  pkg/cloudprovider/provider/packet/provider.go
  pkg/cloudprovider/provider/vsphere/client.go
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider_test.go
  pkg/cloudprovider/provider/vsphere/types/cloudconfig.go
  pkg/cloudprovider/util/cloud_init_settings.go
  pkg/cloudprovider/util/http.go
  pkg/cloudprovider/util/util_test.go
  pkg/clusterinfo/configmap_test.go
  pkg/controller/machinedeployment/util/util.go
  pkg/controller/machineset/delete_policy.go
  pkg/controller/machineset/status.go
  pkg/machines/register.go
  pkg/userdata/helper/kubelet_test.go
  pkg/userdata/sles/provider_test.go
  test/e2e/provisioning/deploymentscenario.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/migrateuidscenario.go
  test/e2e/provisioning/verify.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#959 Add unit tests for tinkerbell
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver_test.go
  pkg/cloudprovider/provider/baremetal/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#969 fix vSphere client not using the provided custom CA bundle
  pkg/cloudprovider/provider/vsphere/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#972 [release/v1.27] fix vSphere client not using the provided custom CA bundle (#969)
  pkg/cloudprovider/provider/vsphere/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#975 use the rhel ga instead of custom image on azure
  .prow.yaml
  pkg/cloudprovider/provider/azure/provider.go
  pkg/userdata/rhel/provider.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-azure-custom-image-reference.yaml
  test/e2e/provisioning/testdata/machinedeployment-azure-redhat-satellite.yaml
  test/e2e/provisioning/testdata/machinedeployment-azure.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#977 add aws-node-termination-handler label for node selector
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#983 Hetzner firewall support
  examples/hetzner-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/hetzner/types/types.go
  test/e2e/provisioning/testdata/machinedeployment-hetzner.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/M
