Repository kubermatic/machine-controller, pull requests merged in 2021-12, with the labels that each got.

#1119 Default flatcar provisionUtility on AWS to cloud-init
  pkg/admission/machines.go
  pkg/providerconfig/types.go
  pkg/providerconfig/types_test.go
  pkg/userdata/flatcar/flatcar.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes

#1116 Fix bootstrapping on digital ocean for ubuntu
  pkg/controller/machine/bootstrap.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes

#1117 Add bootstrapping support for SLES
  pkg/controller/machine/bootstrap.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes

#1121 Merge KubeVirt e2e tests
  .prow.yaml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt-dns-config.yaml
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/L, dco-signoff: yes

#1122 Use cloud-init for Flatcar machines on AWS unconditionally
  pkg/userdata/flatcar/flatcar.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes

#1125 Add support for gp3 disk type in AWS
  .golangci.yml
  pkg/cloudprovider/provider/aws/provider.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes

#1133 New -node-containerd-registry-mirrors flag
  cmd/machine-controller/custom_flags.go
  cmd/machine-controller/main.go
  pkg/containerruntime/containerd.go
  pkg/containerruntime/containerruntime.go
  pkg/containerruntime/docker.go
  pkg/userdata/amzn2/provider_test.go
  pkg/userdata/centos/provider_test.go
  pkg/userdata/flatcar/provider_test.go
  pkg/userdata/helper/helper.go
  pkg/userdata/helper/template_functions.go
  pkg/userdata/rhel/provider_test.go
  pkg/userdata/rhel/testdata/kubelet-v1.22-vsphere-proxy.yaml
  pkg/userdata/sles/provider.go
  pkg/userdata/sles/provider_test.go
  pkg/userdata/ubuntu/provider_test.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes

#1134 Remove unused hyperkube and kubelet repository
  cmd/machine-controller/main.go
  go.mod
  pkg/apis/plugin/plugin.go
  pkg/controller/machine/machine_controller.go
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/provider_test.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes

#1136 Add validation for machinedeployments when using OSM
  cmd/webhook/main.go
  go.mod
  go.sum
  pkg/admission/admission.go
  pkg/admission/machinedeployments.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes

#1139 Fix evictionHard parsing
  pkg/userdata/helper/kubelet.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note, dco-signoff: yes

#1130 Support for Equinix Metal cloud provider
  .prow.yaml
  docs/cloud-provider.md
  docs/operating-system.md
  examples/equinixmetal-machinedeployment.yaml
  pkg/admission/machinedeployments.go
  pkg/admission/machinedeployments_validation.go
  pkg/admission/machines.go
  pkg/admission/util.go
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/equinixmetal/types/types.go
  pkg/providerconfig/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-equinixmetal.yaml
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes

#1141 use kubevirt/api instead of kubevirt/client-go
  go.mod
  go.sum
  pkg/cloudprovider/provider/kubevirt/provider.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes
