Repository kubermatic/machine-controller, pull requests merged in 2021-03, with the labels that each got.

#900 Add application credentials to openstack provider
  examples/openstack-machinedeployment.yaml
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/provider_test.go
  pkg/cloudprovider/provider/openstack/types/cloudconfig.go
  pkg/cloudprovider/provider/openstack/types/cloudconfig_test.go
  pkg/cloudprovider/provider/openstack/types/testdata/use-application-credentials-ignore-userpass.golden
  pkg/cloudprovider/provider/openstack/types/testdata/use-application-credentials.golden
  pkg/cloudprovider/provider/openstack/types/types.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/L

#910 shfmt
  .prow.yaml
  Makefile
  hack/build-kubevirt-images.sh
  hack/ci-download-gocache.sh
  hack/ci-e2e-test.sh
  hack/ci-upload-gocache.sh
  hack/e2e-setup-openstack-images.sh
  hack/setup-openstack-images.sh
  hack/update-fixtures.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#911 handle misconfigured hetzner machines better
  pkg/cloudprovider/provider/hetzner/provider.go
  test/e2e/provisioning/testdata/machinedeployment-hetzner.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#914 Machine settings in annotations
  Makefile
  cmd/machine-controller/main.go
  cmd/webhook/main.go
  pkg/admission/admission.go
  pkg/admission/machines.go
  pkg/apis/cluster/common/consts.go
  pkg/controller/machine/machine_controller.go
  pkg/node/flags.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#915 Update to Go 1.16.1
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#919 Fix health-monitor WRT docker restarts
  pkg/userdata/scripts/health-monitor.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#920 Update hash to health-monitor
  pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.18-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.19-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.20-aws.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.17.16.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.18.14.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.19.4.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.20.1.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.17.16.json
  pkg/userdata/flatcar/testdata/ignition_v1.18.14.json
  pkg/userdata/flatcar/testdata/ignition_v1.19.4.json
  pkg/userdata/flatcar/testdata/ignition_v1.20.1.json
  pkg/userdata/helper/download_binaries_script.go
  pkg/userdata/helper/testdata/safe_download_binaries_v1.20.1.golden
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.18-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.19-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-vsphere.yaml
  pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/sles/testdata/multiple-dns-servers.yaml
  pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
  pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/sles/testdata/openstack.yaml
  pkg/userdata/sles/testdata/version-1.17.16.yaml
  pkg/userdata/sles/testdata/version-1.18.14.yaml
  pkg/userdata/sles/testdata/version-1.19.4.yaml
  pkg/userdata/sles/testdata/version-1.20.1.yaml
  pkg/userdata/sles/testdata/vsphere-mirrors.yaml
  pkg/userdata/sles/testdata/vsphere-proxy.yaml
  pkg/userdata/sles/testdata/vsphere.yaml
  pkg/userdata/ubuntu/testdata/containerd.yaml
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.17.16.yaml
  pkg/userdata/ubuntu/testdata/version-1.18.14.yaml
  pkg/userdata/ubuntu/testdata/version-1.19.4.yaml
  pkg/userdata/ubuntu/testdata/version-1.20.1.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#923 validate operatingSystemSpec is not empty
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/packet/provider.go
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#926 Set OS label on machine.Spec
  pkg/admission/machines.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#928 Fix environment sourcing when containerd is chosen
  pkg/containerruntime/containerd.go
  pkg/userdata/ubuntu/testdata/containerd.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#929 Adding initial baremetal provider structure
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/provider/baremetal/plugins/driver.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/provider/baremetal/types/types.go
  pkg/providerconfig/types/types.go
  test/e2e/provisioning/testdata/machinedeployment-baremetal.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#937 add license check presubmit
  .prow.yaml
  .wwhrd.yml
  hack/verify-licenses.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
