Repository kubermatic/machine-controller, pull requests merged in 2021-07, with the labels that each got.

#1014 Add assignAvailabilitySet to azure machine deployment
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/azure/types/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1021 Cluster-id addition in vsphere cloud-config api
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/types/cloudconfig.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1023 Fix copypaste typo in error message
  pkg/admission/machinedeployments_validation.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1019 Refactor unmarshaling openstack InstanceReadyCheckPeriod InstanceReadyCheckTimeout
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/providerconfig/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1026 Don't delete openstack instances on creation timeout
  pkg/cloudprovider/provider/openstack/helper.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/provider_test.go
  pkg/controller/nodecsrapprover/node_csr_approver_v1beta1.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
