Repository kubermatic/machine-controller, pull requests merged in 2021-02, with the labels that each got.

#886 Retry getting AWS instance
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#885 use quay.io/kubermatic/kubelet
  cmd/machine-controller/main.go
  docs/network-restrictions.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#888 [release/v1.24] use quay.io/kubermatic/kubelet
  cmd/machine-controller/main.go
  docs/network-restrictions.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#892 Support image reference in azure
  .prow.yaml
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/azure/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-azure-custom-image-reference.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#895 add -ca-bundle flag and support for custom CAs to vSphere, Openstack
  .prow.yaml
  cmd/machine-controller/main.go
  cmd/webhook/main.go
  hack/ci-e2e-test.sh
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/vsphere/client.go
  pkg/cloudprovider/util/http.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machine-openstack.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#901 Create workaround for kubelet stopped posting node status bug
  pkg/userdata/scripts/health-monitor.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/M

#902 Updated health monitor
  pkg/userdata/centos/testdata/kubelet-v1.17-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.17-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.18-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.19-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.20-aws.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.17.16.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.18.14.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.19.4.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.20.1.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.17.16.json
  pkg/userdata/flatcar/testdata/ignition_v1.18.14.json
  pkg/userdata/flatcar/testdata/ignition_v1.19.4.json
  pkg/userdata/flatcar/testdata/ignition_v1.20.1.json
  pkg/userdata/helper/download_binaries_script.go
  pkg/userdata/helper/testdata/safe_download_binaries_v1.20.1.golden
  pkg/userdata/rhel/testdata/kubelet-v1.17-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.18-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.19-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-vsphere.yaml
  pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/sles/testdata/multiple-dns-servers.yaml
  pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
  pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/sles/testdata/openstack.yaml
  pkg/userdata/sles/testdata/version-1.17.16.yaml
  pkg/userdata/sles/testdata/version-1.18.14.yaml
  pkg/userdata/sles/testdata/version-1.19.4.yaml
  pkg/userdata/sles/testdata/version-1.20.1.yaml
  pkg/userdata/sles/testdata/vsphere-mirrors.yaml
  pkg/userdata/sles/testdata/vsphere-proxy.yaml
  pkg/userdata/sles/testdata/vsphere.yaml
  pkg/userdata/ubuntu/testdata/containerd.yaml
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.17.16.yaml
  pkg/userdata/ubuntu/testdata/version-1.18.14.yaml
  pkg/userdata/ubuntu/testdata/version-1.19.4.yaml
  pkg/userdata/ubuntu/testdata/version-1.20.1.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
