Repository kubermatic/machine-controller, pull requests merged in 2021-04, with the labels that each got.

#930 Add tinkerbell as baremetal driver
  go.mod
  go.sum
  pkg/cloudprovider/provider/baremetal/plugins/driver.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/common.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/hardware.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/template.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/workflow.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/hardware.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/template.go
  pkg/cloudprovider/provider/baremetal/provider.go
  test/e2e/provisioning/testdata/machinedeployment-baremetal-tinkerbell.yaml
  test/e2e/provisioning/testdata/machinedeployment-baremetal.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#807 Fix free floating IP detection logic for OTC
  pkg/cloudprovider/provider/openstack/helper.go
Labels: approved, dco-signoff: yes, lgtm, priority/low, release-note-none, sig/cluster-management, size/XS

#941 Support cloud-init bootstrap generating
  pkg/cloudprovider/util/cloud_init_settings.go
  pkg/cloudprovider/util/cloud_init_settings_test.go
  pkg/cloudprovider/util/testdata/expected_userdata.yaml
  pkg/cloudprovider/util/testdata/userdata.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#947 Cloud init refactoring
  pkg/cloudprovider/provider/baremetal/plugins/driver.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/template.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/util/cloud_init_settings.go
  pkg/cloudprovider/util/cloud_init_settings_test.go
  pkg/cloudprovider/util/testdata/expected_userdata.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#948 Support Nautobot client in machine controller
  pkg/nautobot/client.go
  pkg/nautobot/common.go
  pkg/nautobot/device.go
  pkg/nautobot/interface.go
  pkg/nautobot/ip.go
  pkg/nautobot/prefix.go
  pkg/nautobot/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#950 Fix RHEL subscription deregistration on OpenStack
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.20-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-vsphere.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#949 Integrate nautobot client in baremetal provider
  cmd/machine-controller/main.go
  pkg/cloudprovider/provider/baremetal/metadata/nautobot/client.go
  pkg/cloudprovider/provider/baremetal/plugins/driver.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/common.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/hardware.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/hardware.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/template.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/provider/baremetal/types/types.go
  pkg/nautobot/client.go
  pkg/nautobot/device.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#954 [release/v1.19] Retry getting AWS instance (#886)
  pkg/cloudprovider/provider/aws/provider.go
  test/tools/integration/Makefile
  test/tools/integration/versions.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M
