Repository kubermatic/machine-controller, pull requests merged in 2021-01, with the labels that each got.

#868 Reserve an IP address before creating VM at Anexia Cloud
  examples/anexia-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/types/types.go
  test/e2e/provisioning/testdata/machinedeployment-anexia.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#863 Update to controller-runtime 0.7.0
  cmd/machine-controller/main.go
  examples/machine-controller.yaml
  go.mod
  go.sum
  hack/run-machine-controller.sh
  pkg/admission/admission.go
  pkg/admission/machinedeployments.go
  pkg/admission/machines.go
  pkg/apis/cluster/v1alpha1/register.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/clusterinfo/configmap_test.go
  pkg/controller/machine/kubeconfig.go
  pkg/controller/machine/kubeconfig_test.go
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_test.go
  pkg/controller/machine/metrics.go
  pkg/controller/machinedeployment/machinedeployment_controller.go
  pkg/controller/machinedeployment/rolling.go
  pkg/controller/machinedeployment/sync.go
  pkg/controller/machineset/delete_policy.go
  pkg/controller/machineset/machine.go
  pkg/controller/machineset/machineset_controller.go
  pkg/controller/machineset/status.go
  pkg/controller/nodecsrapprover/node_csr_approver.go
  pkg/health/readiness.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/lifecycle

#874 Specify resource group field for azure vnet
  docs/cloud-provider.md
  examples/azure-machinedeployment.yaml
  pkg/cloudprovider/provider/azure/create_delete_resources.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/azure/types/cloudconfig.go
  pkg/cloudprovider/provider/azure/types/types.go
  test/e2e/provisioning/testdata/machinedeployment-azure-redhat-satellite.yaml
  test/e2e/provisioning/testdata/machinedeployment-azure.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#879 Remove defective tab from cloud-init metadata
  pkg/cloudprovider/provider/vsphere/helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS, team/lifecycle

#870 Add optional use-octavia flag to OpenStack cloud config
  pkg/cloudprovider/provider/openstack/types/cloudconfig.go
  pkg/cloudprovider/provider/openstack/types/cloudconfig_test.go
  pkg/cloudprovider/provider/openstack/types/testdata/use-octavia-explicitly-disabled.golden
  pkg/cloudprovider/provider/openstack/types/testdata/use-octavia-explicitly-enabled.golden
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#880 fix missing machine metrics
  cmd/machine-controller/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS, team/lifecycle

#881 Fix containerd install on ubuntu
  pkg/containerruntime/containerd.go
  pkg/userdata/ubuntu/provider_test.go
  pkg/userdata/ubuntu/testdata/containerd.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#882 Fix kubelet systemd unit service dependency on the correct container runtime
  pkg/userdata/centos/provider.go
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/kubelet_test.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/sles/provider.go
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/containerd.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M
