Repository kubermatic/machine-controller, pull requests merged in 2022-05, with the labels that each got.

#1275 Remove obsolete testdata for old Kubernetes patch versions
  pkg/userdata/amzn2/testdata/containerd-kubelet-v1.20-aws.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.20-aws.yaml
  pkg/userdata/centos/testdata/kubelet-containerd-v1.20-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.20-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-nutanix.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.20.14.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.21.8.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.22.5.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.23.0.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.20.14.json
  pkg/userdata/flatcar/testdata/ignition_v1.21.8.json
  pkg/userdata/flatcar/testdata/ignition_v1.22.5.json
  pkg/userdata/flatcar/testdata/ignition_v1.23.0.json
  pkg/userdata/helper/testdata/download_binaries_v1.20.14.golden
  pkg/userdata/helper/testdata/download_binaries_v1.21.8.golden
  pkg/userdata/helper/testdata/download_binaries_v1.22.5.golden
  pkg/userdata/helper/testdata/download_binaries_v1.23.0.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.20.14-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.20.14.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.21.8-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.21.8.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.22.5-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.22.5.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.23.0-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.23.0.golden
  pkg/userdata/rhel/testdata/kubelet-containerd-v1.20-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-containerd-v1.20-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.20-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.21-nutanix.yaml
  pkg/userdata/sles/testdata/version-1.20.14.yaml
  pkg/userdata/sles/testdata/version-1.21.8.yaml
  pkg/userdata/sles/testdata/version-1.22.5.yaml
  pkg/userdata/sles/testdata/version-1.23.0.yaml
  pkg/userdata/ubuntu/testdata/version-1.20.14.yaml
  pkg/userdata/ubuntu/testdata/version-1.21.8.yaml
  pkg/userdata/ubuntu/testdata/version-1.22.5.yaml
  pkg/userdata/ubuntu/testdata/version-1.23.0.yaml
Labels: approved, lgtm, release-note-none, size/XXL, dco-signoff: yes, sig/osm

#1271 Flatcar: explicitly stop masked units on first boot
  hack/lib.sh
  hack/update-fixtures.sh
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/testdata/ignition_v1.21.10.json
  pkg/userdata/flatcar/testdata/ignition_v1.22.7.json
  pkg/userdata/flatcar/testdata/ignition_v1.23.5.json
  pkg/userdata/flatcar/testdata/ignition_v1.24.0.json
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, sig/osm

#1277 Update containerd to 1.5 for all Kubernetes versions
  pkg/containerruntime/containerd.go
  pkg/containerruntime/containerruntime.go
  pkg/userdata/ubuntu/testdata/containerd.yaml
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes, sig/osm

#1280 enable DHCPv6 on RHEL
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-nutanix.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.24-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.24-aws.yaml
  pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
Labels: approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm

#1282 Remove use-osm flag from run-machine-controller script
  hack/run-machine-controller.sh
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1283 remove check for dualstack unsupported zones in GCP
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/gce/provider_test.go
Labels: approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm

#1286 Fix cleanup for machines on azure
  go.mod
  go.sum
  pkg/cloudprovider/provider/azure/provider.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes, sig/osm

#1287 Only attempt resource deletion in azure provider if finalizer is set
  pkg/cloudprovider/provider/azure/create_delete_resources.go
  pkg/cloudprovider/provider/azure/provider.go
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1289 update to controller-runtime 0.12, k8s 1.24.0
  go.mod
  go.sum
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes

#1288 docs(anexia): add info for templates
  docs/anexia.md
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes

#1265 rh_subscriprion bootstrap script
  pkg/cloudprovider/provider/azure/provider.go
  pkg/controller/machine/bootstrap.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-nutanix.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.24-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.24-aws.yaml
  pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1290 Split prowjobs; move them to .prow directory
  .prow.yaml
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/XXL, dco-signoff: yes

#1293 Upgrade to Go 1.18.2
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-fixtures.sh
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes

#1294 Contexts, contexts everywhere.
  cmd/machine-controller/main.go
  pkg/admission/machines.go
  pkg/apis/cluster/v1alpha1/migrations/migrations.go
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/anexia/utils/utils.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/gce/provider_test.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/provider_test.go
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/cloudprovider/provider/vsphere/client.go
  pkg/cloudprovider/provider/vsphere/helper_test.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/provider_test.go
  pkg/cloudprovider/types/types.go
  pkg/cloudprovider/validationwrapper.go
  pkg/controller/machine/machine_controller.go
  pkg/rhsm/subscription_manager.go
  pkg/rhsm/subscription_manager_test.go
  pkg/signals/signal.go
  test/e2e/provisioning/migrateuidscenario.go
Labels: sig/cluster-management, size/XL, approved, lgtm, release-note-none, dco-signoff: yes, sig/osm

#1295 Disable e2e tests for Nutanix
  .prow/provider-nutanix.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1302 Update package repo path for Buildah
  test/tools/integration/master_install_script.sh
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1301 Refactor handling of Kubeconfig for KubeVirt
  examples/kubevirt-machinedeployment.yaml
  pkg/cloudprovider/provider/kubevirt/provider.go
  test/e2e/provisioning/all_e2e_test.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1306 Refactor handling of kubeconfig for kubevirt
  pkg/cloudprovider/provider/kubevirt/provider.go
  test/e2e/provisioning/all_e2e_test.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1297 docs: include rocky linux in compatibility matrix
  docs/operating-system.md
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes

#1307 Switch to Ubuntu 22.04 LTS for e2e tests
  Dockerfile
  test/tools/integration/hetzner.tf
  test/tools/integration/master_install_script.sh
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes

#1300 Add support for VMware Cloud Director as cloud provider
  .gitignore
  .prow/provider-vcloud-director.yaml
  .wwhrd.yml
  README.md
  cmd/provision/README.md
  docs/operating-system.md
  docs/vmware-cloud-director.md
  examples/vmware-cloud-director-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/provider/vmware-cloud-director/client.go
  pkg/cloudprovider/provider/vmware-cloud-director/helper.go
  pkg/cloudprovider/provider/vmware-cloud-director/provider.go
  pkg/cloudprovider/provider/vmware-cloud-director/types/types.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/providerconfig/types/types.go
  pkg/userdata/amzn2/provider.go
  pkg/userdata/centos/provider.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/rockylinux/provider.go
  pkg/userdata/sles/provider.go
  pkg/userdata/ubuntu/provider.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-vmware-cloud-director.yaml
Labels: sig/cluster-management, approved, lgtm, release-note, size/XXL, dco-signoff: yes, sig/osm

#1311 Set computer name for VCD VMs
  pkg/cloudprovider/provider/vmware-cloud-director/helper.go
  pkg/cloudprovider/provider/vmware-cloud-director/provider.go
Labels: approved, lgtm, release-note-none, size/S, dco-signoff: yes, sig/osm

#1312 Block setting spec.ConfigSource for Kubernetes 1.24+
  pkg/admission/machines.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes

#1315 Load IPv6 address on Azure only if IPFamily is IPv6 or Dualstack
  pkg/cloudprovider/provider/azure/provider.go
Labels: approved, lgtm, release-note, size/S, dco-signoff: yes, sig/osm

#1317 Support configuring MaxPods for Machines
  pkg/apis/cluster/common/consts.go
  pkg/userdata/helper/kubelet.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes, sig/osm
