Repository kubermatic/machine-controller, pull requests merged in 2022-02, with the labels that each got.

#1182 Change baseurl to vault.centos.org for CentOS 8
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-containerd-v1.20-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.20-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-nutanix.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-aws.yaml
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1183 Apply band-aid to reanimate CentOS8 bootstraping
  pkg/controller/machine/bootstrap.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note, dco-signoff: yes

#1184 Introduce Hetzner placement groups into machinedeployments
  examples/hetzner-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/hetzner/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, needs-ok-to-test, dco-signoff: yes, sig/osm

#1145 Add E2E test case for Nutanix cloud provider
  .prow.yaml
  hack/ci-e2e-test.sh
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-nutanix.yaml
  test/tools/integration/hetzner.tf
  test/tools/integration/master_install_script.sh
  test/tools/integration/output.tf
  test/tools/integration/provision_master.sh
  test/tools/integration/variables.tf
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/L, dco-signoff: yes

#1185 Sets kubelet ContainerLog settings when docker is used
  pkg/userdata/helper/kubelet.go
Labels: approved, lgtm, release-note-none, size/S, dco-signoff: yes, sig/osm

#1187 Remove cluster field from vSphere provider
  examples/vsphere-datastore-cluster-machinedeployment.yaml
  examples/vsphere-machinedeployment.yaml
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/provider_test.go
  pkg/cloudprovider/provider/vsphere/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes, sig/osm

#1186 Unmarshal provider configs in strict mode
  cmd/machine-controller/main.go
  examples/openstack-machinedeployment.yaml
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/alibaba/types/types.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/types/types.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/aws/types/types.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/azure/types/types.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/provider/baremetal/types/types.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/digitalocean/types/types.go
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/equinixmetal/types/types.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/gce/types/types.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/hetzner/types/types.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/types/types.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/linode/types/types.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/nutanix/types/types.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/types/types.go
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/cloudprovider/provider/scaleway/types/types.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/types/types.go
  pkg/jsonutil/strict.go
  pkg/providerconfig/types/types.go
  test/e2e/provisioning/testdata/machinedeployment-openstack-upgrade.yml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
Labels: sig/cluster-management, size/XL, approved, lgtm, release-note, dco-signoff: yes, sig/osm

#1188 fix: returned vSphere RawConfig.Cluster
  pkg/cloudprovider/provider/vsphere/types/types.go
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes, sig/osm

#1198 Validate max price in spot instance request
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, lgtm, size/XS, release-note-none, dco-signoff: yes, sig/osm
