Repository kubermatic/machine-controller, pull requests merged in 2022-07, with the labels that each got.

#1344 Azure: Support for accelerated networking
  pkg/cloudprovider/provider/azure/create_delete_resources.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/azure/types/types.go
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1346 Improvements for CI
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Makefile
  hack/ci/download-gocache.sh
  hack/ci/setup-kind-cluster.sh
  hack/ci/upload-gocache.sh
  test/e2e/provisioning/testdata/machinedeployment-aws-arm-machines.yaml
  test/e2e/provisioning/testdata/machinedeployment-aws-ebs-encryption-enabled.yaml
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/L, dco-signoff: yes

#1343 Remove support for Kubernetes 1.21
  README.md
  pkg/userdata/amzn2/provider_test.go
  pkg/userdata/amzn2/testdata/kubelet-v1.21-aws-external.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-vsphere-mirrors.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/centos/provider_test.go
  pkg/userdata/centos/testdata/kubelet-v1.21-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/flatcar/provider_test.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.21.10.yaml
  pkg/userdata/flatcar/testdata/containerd.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.21.10.json
  pkg/userdata/helper/common_test.go
  pkg/userdata/helper/testdata/download_binaries_v1.21.10.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.21.10-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.21.10.golden
  pkg/userdata/rhel/provider_test.go
  pkg/userdata/rhel/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/rockylinux/provider_test.go
  pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere-mirrors.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/sles/provider_test.go
  pkg/userdata/ubuntu/provider_test.go
  pkg/userdata/ubuntu/testdata/nutanix.yaml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/XXL, dco-signoff: yes, sig/osm

#1358 [release/v1.45] Refactor handling of kubeconfig for kubevirt
  pkg/cloudprovider/provider/kubevirt/provider.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1360 [release/v1.37] Refactor handling of kubeconfig for kubevirt
  pkg/cloudprovider/provider/kubevirt/provider.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes

#1336 set --node-ip depending on external CCM availaibilty in dualstack
  hack/run-machine-controller.sh
  pkg/userdata/amzn2/provider.go
  pkg/userdata/centos/provider.go
  pkg/userdata/flatcar/provider.go
  pkg/userdata/helper/helper.go
  pkg/userdata/helper/kubelet.go
  pkg/userdata/helper/kubelet_test.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/rockylinux/provider.go
  pkg/userdata/sles/provider.go
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/provider_test.go
  pkg/userdata/ubuntu/testdata/digitalocean-dualstack.yaml
  pkg/userdata/ubuntu/testdata/openstack-dualstack.yaml
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/XXL, dco-signoff: yes, sig/osm

#1359 [release/v1.36] Refactor handling of kubeconfig for kubevirt
  pkg/cloudprovider/provider/kubevirt/provider.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt-dns-config.yaml
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1365 Disable a subset of azure tests temporarily
  test/e2e/provisioning/all_e2e_test.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1363 Equinix: use m3.small.x86 for CentOS E2E tests
  test/e2e/provisioning/helper.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1367 Fix unmarshalling for `configvarstring` in cloudProviderSpec
  pkg/providerconfig/types/types.go
  pkg/providerconfig/types/types_test.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes

#1351 Fix logic for finding node by ProviderID
  pkg/cloudprovider/instance/instance.go
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/anexia/instance.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/gce/instance.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/cloudprovider/provider/vmwareclouddirector/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_test.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, sig/osm

#1371 fix typos
  cmd/machine-controller/main.go
  examples/openstack-machinedeployment.yaml
  pkg/apis/cluster/v1alpha1/migrations/migrations.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/anexia/types/errors.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
  pkg/cloudprovider/provider/nutanix/client.go
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/controller/machine/kubeconfig_test.go
  pkg/controller/machine/machine_test.go
  pkg/userdata/amzn2/provider_test.go
  pkg/userdata/centos/provider_test.go
  pkg/userdata/rhel/provider_test.go
  pkg/userdata/rockylinux/provider_test.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/deploymentscenario.go
  test/e2e/provisioning/verify.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm

#1373 [release/v1.43] Fix logic for finding node by ProviderID
  .prow.yaml
  pkg/cloudprovider/instance/instance.go
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/anexia/instance.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/gce/instance.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-equinixmetal.yaml
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, sig/osm

#1369 Enable OperatingSystemManager in E2E tests
  .prow/provider-aws.yaml
  examples/machine-controller.yaml
  examples/operating-system-manager.yaml
  go.mod
  go.sum
  hack/ci/run-e2e-tests.sh
  hack/ci/setup-machine-controller-in-kind.sh
  hack/run-machine-controller.sh
  pkg/admission/machinedeployments_validation.go
  pkg/admission/machines.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/vmwareclouddirector/helper.go
  pkg/cloudprovider/provider/vmwareclouddirector/provider.go
  pkg/controller/machine/bootstrap.go
  pkg/providerconfig/types.go
  pkg/providerconfig/types_test.go
  pkg/userdata/flatcar/flatcar.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-anexia.yaml
Labels: sig/cluster-management, approved, lgtm, size/XXL, release-note-action-required, dco-signoff: yes, sig/osm

#1379 Enable --resolv-conf=/run/systemd/resolve/resolv.conf kubelet flag for Flatcar
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.22.7.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.23.5.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.24.0.yaml
  pkg/userdata/flatcar/testdata/containerd.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.22.7.json
  pkg/userdata/flatcar/testdata/ignition_v1.23.5.json
  pkg/userdata/flatcar/testdata/ignition_v1.24.0.json
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1382 Add label on machine to differentiate between the tool used for managing machine configurations
  pkg/admission/machines.go
  pkg/controller/util/machine.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes

#1383 Update OSM to v0.6.0
  examples/operating-system-manager.yaml
  go.mod
  go.sum
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes
