Repository kubermatic/machine-controller, pull requests merged in 2022-03, with the labels that each got.

#1190 Waiting for volumeAttachments deletion
  examples/machine-controller.yaml
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_test.go
  pkg/node/eviction/eviction.go
  pkg/node/nodemanager/node_manager.go
  pkg/node/poddeletion/pod_deletion.go
Labels: sig/cluster-management, size/XL, approved, lgtm, release-note-none, dco-signoff: yes

#1206 [release/v1.36] Waiting for volumeAttachments deletion (#1190)
  examples/machine-controller.yaml
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/machine_test.go
  pkg/node/eviction/eviction.go
  pkg/node/nodemanager/node_manager.go
  pkg/node/poddeletion/pod_deletion.go
Labels: sig/cluster-management, size/XL, approved, release-note, dco-signoff: yes

#1201 Update Azure SDK and API version
  go.mod
  go.sum
  pkg/cloudprovider/provider/azure/create_delete_resources.go
  pkg/cloudprovider/provider/azure/get_client.go
  pkg/cloudprovider/provider/azure/provider.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1210 Enhance OpenStack app credentials support
  docs/cloud-provider.md
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/types/cloudconfig.go
  pkg/cloudprovider/provider/openstack/types/testdata/use-application-credentials-ignore-userpass.golden
  pkg/cloudprovider/provider/openstack/types/testdata/use-application-credentials.golden
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes, sig/osm

#1215 Alibaba Images names
  pkg/cloudprovider/provider/alibaba/provider.go
  test/e2e/provisioning/all_e2e_test.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, sig/osm

#1207 consider pod cidr information during instance creation
  cmd/machine-controller/main.go
  pkg/apis/plugin/plugin.go
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/provider_test.go
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/types/types.go
  pkg/cloudprovider/validationwrapper.go
  pkg/controller/machine/machine_controller.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/provider_test.go
  pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
  test/e2e/provisioning/migrateuidscenario.go
Labels: sig/cluster-management, size/XL, approved, lgtm, release-note-none, dco-signoff: yes, sig/osm

#1218 Refactor controller utilities
  pkg/controller/machine/machine_controller.go
  pkg/controller/machinedeployment/rolling.go
  pkg/controller/machinedeployment/sync.go
  pkg/controller/util/machine.go
  pkg/controller/util/machine_deployment.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/L, dco-signoff: yes

#1175 Make anexia provider more resilient against errors
  go.mod
  go.sum
  pkg/cloudprovider/provider/anexia/helper_test.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/anexia/types/errors.go
  pkg/cloudprovider/provider/anexia/types/types.go
  pkg/cloudprovider/provider/anexia/utils/utils.go
Labels: sig/cluster-management, size/XL, approved, lgtm, release-note, ok-to-test, dco-signoff: yes, sig/osm

#1223 Add Helene and Sankalp to OWNERS_ALIASES
  .gitignore
  OWNERS_ALIASES
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1217 Kubevirt Add common label to all VMs linked to the same MachineDeployment
  examples/kubevirt-machinedeployment.yaml
  pkg/cloudprovider/provider/kubevirt/provider.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes, sig/osm

#1222 New -kubernetes-version-constraints webhook flag
  cmd/webhook/main.go
  pkg/admission/admission.go
  pkg/admission/machines.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes

#1226 Disable firewalld on supported OSes
  pkg/userdata/amzn2/provider.go
  pkg/userdata/amzn2/testdata/containerd-kubelet-v1.20-aws.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.20-aws.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-aws-external.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-vsphere-mirrors.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-vsphere-proxy.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-vsphere.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-containerd-v1.20-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.20-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-nutanix.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-containerd-v1.20-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.20-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-nutanix.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1213 Add tag support for vSphere provider
  pkg/cloudprovider/provider/vsphere/client.go
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/types/types.go
Labels: approved, lgtm, size/L, release-note, dco-signoff: yes, sig/osm

#1228 Remove 'alpha' status of Nutanix implementation
  docs/nutanix.md
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1219 Flatcar stop disabled units
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.20.14.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.21.8.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.22.5.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.23.0.yaml
  pkg/userdata/flatcar/testdata/containerd.yaml
Labels: approved, lgtm, release-note, size/S, ok-to-test, dco-signoff: yes, sig/osm

#1229 Revert "assign ipv6 address to aws"
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/kubevirt/types/types.go
  pkg/cloudprovider/util/net.go
  pkg/node/poddeletion/pod_deletion.go
  test/e2e/provisioning/migrateuidscenario.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm

#1234 revert network config
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/provider_test.go
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/types/types.go
  pkg/cloudprovider/validationwrapper.go
  pkg/controller/machine/machine_controller.go
  test/e2e/provisioning/migrateuidscenario.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm
