Repository kubermatic/machine-controller, pull requests merged in 2022-11, with the labels that each got.

#1473 Fix static network rendering for flatcar
  pkg/userdata/flatcar/provider.go
Labels: kind/bug, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, sig/osm, docs/none

#1471 add optional additional subnets to Nutanix provider
  examples/nutanix-machinedeployment.yaml
  pkg/cloudprovider/provider/nutanix/client.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/nutanix/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-nutanix.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, ok-to-test, kind/feature, dco-signoff: yes, sig/osm, docs/tbd

#1476 restart containerd for flatcar so the drop in conf will be considered
  pkg/containerruntime/containerd.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.24.0.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.25.0.yaml
  pkg/userdata/flatcar/testdata/containerd.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.24.0.json
  pkg/userdata/flatcar/testdata/ignition_v1.25.0.json
Labels: kind/bug, sig/cluster-management, approved, lgtm, release-note-none, size/S, ok-to-test, dco-signoff: yes, sig/osm, docs/none

#1477 Update GitHub URL references to use main branch
  cmd/machine-controller/main.go
  code-of-conduct.md
  docs/kubevirt.md
  pkg/cloudprovider/provider/vsphere/network.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, sig/osm, kind/chore, docs/none

#1482 Fix e2e tests: Update CentOS image filters & vcenter datastores
  pkg/cloudprovider/provider/aws/provider.go
  test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note, dco-signoff: yes, sig/osm, docs/none

#1480 KubeVirt cleanup small wrong code (preference error check)
  pkg/cloudprovider/provider/kubevirt/provider.go
Labels: kind/cleanup, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, sig/virtualization, sig/osm, docs/none

#1470 add http source for kubevirt VM Disk Image
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
  pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/types/types.go
Labels: approved, lgtm, size/L, release-note, kind/feature, dco-signoff: yes, sig/virtualization, sig/osm, docs/tbd

#1483 Anexia Provider: Utilize `Creating` state instead of blocking `Create` call
  pkg/cloudprovider/provider/anexia/helper_test.go
  pkg/cloudprovider/provider/anexia/instance.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
Labels: approved, lgtm, size/L, release-note, ok-to-test, dco-signoff: yes, sig/osm, docs/none

#1491 KubeVirt deprecate Flavor - no migration
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
  pkg/cloudprovider/provider/kubevirt/testdata/flavor.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/instancetype-flavor.yaml
  pkg/cloudprovider/provider/kubevirt/types/types.go
Labels: approved, lgtm, size/L, release-note, kind/feature, dco-signoff: yes, sig/osm, docs/tbd

#1485 [release/v1.42] Update filter for CentOS Linux images
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes, sig/osm

#1494 KubeVirt small cleanup: Flavor and PodAffinity
  examples/kubevirt-machinedeployment.yaml
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes, docs/none

#1487 [release/v1.54] Update filter for CentOS Linux images
  pkg/cloudprovider/provider/aws/provider.go
  test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note, dco-signoff: yes, sig/osm

#1472 Add cluster labels to kubevirt vm
  docs/kubevirt.md
  examples/kubevirt-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
  pkg/cloudprovider/provider/kubevirt/testdata/affinity.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/custom-local-disk.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-custom.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-standard.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/nominal-case.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/secondary-disks.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/topologyspreadconstraints.yaml
  pkg/cloudprovider/provider/kubevirt/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm, docs/none

#1496 Set ownership for kubevirt provider to sig-virt
  OWNERS_ALIASES
  pkg/cloudprovider/provider/kubevirt/OWNERS
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes, sig/osm, docs/none

#1499 Update trigger condition for cloud provider specific E2E jobs
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-openstack.yaml
  .prow/provider-vsphere.yaml
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes, kind/chore, docs/none

#1498 Update OSM deployment for E2E tests
  examples/operating-system-manager.yaml
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/XXL, dco-signoff: yes, kind/chore, docs/none
