Repository kubermatic/machine-controller, pull requests merged in 2022-01, with the labels that each got.

#1132 Nutanix cloud provider support
  .wwhrd.yml
  docs/nutanix.md
  examples/nutanix-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/provider/nutanix/client.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/nutanix/types/types.go
  pkg/providerconfig/types/types.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/XXL, dco-signoff: yes

#1146 Add SIG osm for overseeing changes for userdata and cloudprovider
  OWNERS_ALIASES
  pkg/cloudprovider/provider/OWNERS
  pkg/userdata/OWNERS
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes

#1150 Move spot instance e2e test to different AZ in eu-central-1
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-aws-spot-instances.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1148 Fix disk size calculation in Nutanix spec validation
  pkg/cloudprovider/provider/nutanix/provider.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, sig/osm

#1147 Use default scheme and pass request context to ConfigVarResolver
  cmd/webhook/main.go
  pkg/admission/admission.go
  pkg/admission/machinedeployments.go
  pkg/admission/machines.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes

#1075 Use appropriate base64 flags
  Makefile
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1149 Add mutating logic to populate OSP annotation based on OS flavor
  pkg/admission/machinedeployments.go
  pkg/admission/machinedeployments_validation.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes

#1140 update cri defaulting
  pkg/containerruntime/containerruntime.go
  pkg/userdata/amzn2/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.22.2.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.22.2.json
  pkg/userdata/rhel/testdata/kubelet-v1.22-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-vsphere.yaml
  pkg/userdata/ubuntu/testdata/version-1.22.2.yaml
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/L, dco-signoff: yes, sig/osm

#1152 Nutanix: Add support for proxy URL setting
  go.mod
  go.sum
  pkg/cloudprovider/provider/nutanix/client.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/nutanix/types/types.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes, sig/osm

#1144 Containerd daemon level registry auth configuration
  .gimps.yaml
  cmd/machine-controller/main.go
  docs/registry-authentication.md
  pkg/admission/machinedeployments_validation.go
  pkg/containerruntime/containerd.go
  pkg/containerruntime/containerruntime.go
  pkg/controller/machine/machine_controller.go
  pkg/userdata/helper/helper.go
  pkg/userdata/helper/kubelet.go
  pkg/userdata/ubuntu/provider_test.go
  pkg/userdata/ubuntu/testdata/containerd.yaml
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, sig/osm

#1153 Split clients into worker and seed(default) clients for webhooks
  cmd/webhook/main.go
  pkg/admission/admission.go
  pkg/admission/machines.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes

#1156 add bootstrap kubeconfig to the osm bootstraping
  pkg/controller/machine/bootstrap.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes

#1155 Rename NUTANIX_ALLOW_INSECURE to NUTANIX_INSECURE
  pkg/cloudprovider/provider/nutanix/provider.go
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes, sig/osm

#1160 fix cloud config ignition selection
  pkg/controller/machine/bootstrap.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes

#1159 Fixes for bootstrapping config on OpenStack
  go.mod
  go.sum
  pkg/admission/machinedeployments_validation.go
  pkg/controller/machine/bootstrap.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes

#1162 Differentiate CloudProviderName and KubeletCloudProviderName in templates
  pkg/apis/plugin/plugin.go
  pkg/controller/machine/machine_controller.go
  pkg/userdata/amzn2/provider.go
  pkg/userdata/amzn2/provider_test.go
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/provider_test.go
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/provider_test.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/provider_test.go
  pkg/userdata/sles/provider.go
  pkg/userdata/sles/provider_test.go
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/provider_test.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, sig/osm

#1154 Actually read environment variable in GetConfigVarBoolValueOrEnv
  .prow.yaml
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/providerconfig/types.go
  pkg/providerconfig/types/types.go
  pkg/providerconfig/types/types_test.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, sig/osm

#1165 Omit null value from marshalled JSON for ConfigVarBool
  pkg/providerconfig/types/types.go
  pkg/providerconfig/types/types_test.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes

#1163 set the machine_controller_workers metric to an actual value
  pkg/controller/machine/machine_controller.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note, dco-signoff: yes

#1168 Bump osm to 0.3.9
  go.mod
  go.sum
Labels: sig/cluster-management, size/XL, approved, lgtm, release-note-none, dco-signoff: yes

#1169 Configure server group of the openstack VM
  examples/openstack-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/types/types.go
Labels: sig/cluster-management, size/XL, approved, lgtm, release-note, dco-signoff: yes, sig/osm

#1172 disable vSphere tests
  .prow.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1171 update machine controller openstack rhel image
  test/e2e/provisioning/helper.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1174 Improve generation for container runtime configuration
  cmd/machine-controller/main.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/containerruntime/config.go
  pkg/containerruntime/containerruntime.go
  pkg/containerruntime/flags.go
  pkg/controller/machine/machine_controller.go
  pkg/machines/v1alpha1/zz_generated.deepcopy.go
  pkg/userdata/amzn2/provider_test.go
  pkg/userdata/centos/provider_test.go
  pkg/userdata/flatcar/provider_test.go
  pkg/userdata/rhel/provider_test.go
  pkg/userdata/sles/provider_test.go
  pkg/userdata/ubuntu/provider_test.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/L, dco-signoff: yes, sig/osm

#1176 Enable SeccompDefault setting if kubelet feature gate is passed
  pkg/userdata/helper/kubelet.go
Labels: approved, lgtm, size/XS, release-note, dco-signoff: yes, sig/osm

#1170 Update compatibility-matrix
  docs/operating-system.md
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes
