Repository kubermatic/machine-controller, pull requests merged in 2022-06, with the labels that each got.

#1304 Use kind for E2E tests
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vsphere.yaml
  Makefile
  README.md
  cmd/machine-controller/main.go
  examples/machine-controller.yaml
  hack/ci-e2e-test.sh
  hack/ci/cleanup.sh
  hack/ci/download-gocache.sh
  hack/ci/run-e2e-tests.sh
  hack/ci/setup-cni-in-kind.sh
  hack/ci/setup-kind-cluster.sh
  hack/ci/setup-machine-controller-in-kind.sh
  hack/ci/upload-gocache.sh
  hack/cleanup_machines.sh
  hack/lib.sh
  pkg/controller/machine/kubeconfig.go
  pkg/controller/machine/machine_controller.go
  test/e2e/provisioning/all_e2e_test.go
  test/tools/integration/Makefile
  test/tools/integration/README.md
  test/tools/integration/hetzner.tf
  test/tools/integration/master_install_script.sh
  test/tools/integration/output.tf
  test/tools/integration/provider.tf.disabled
  test/tools/integration/provision_master.sh
  test/tools/integration/variables.tf
  test/tools/integration/versions.tf
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/XXL, dco-signoff: yes

#1316 Enable setup.service and disable it after first run
  .prow/provider-vcloud-director.yaml
  pkg/userdata/amzn2/provider.go
  pkg/userdata/amzn2/testdata/kubelet-v1.21-aws-external.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-vsphere-mirrors.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-vsphere-proxy.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-vsphere.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.24-aws.yaml
  pkg/userdata/centos/provider.go
  pkg/userdata/centos/testdata/kubelet-v1.21-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-nutanix.yaml
  pkg/userdata/centos/testdata/kubelet-v1.24-aws.yaml
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-nutanix.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.24-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.24-aws.yaml
  pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
  pkg/userdata/rockylinux/provider.go
  pkg/userdata/rockylinux/testdata/kubelet-v1.21-aws-external.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere-mirrors.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere-proxy.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-nutanix.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.24-aws.yaml
  pkg/userdata/ubuntu/provider.go
  pkg/userdata/ubuntu/testdata/containerd.yaml
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/docker.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/nutanix.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.21.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.22.7.yaml
  pkg/userdata/ubuntu/testdata/version-1.23.5.yaml
  pkg/userdata/ubuntu/testdata/version-1.24.0.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, sig/osm

#1322 Reduce instance profile validation to existence check
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, lgtm, release-note, size/S, dco-signoff: yes, sig/osm

#1323 add dual stack support for DigitalOcean
  pkg/cloudprovider/provider/digitalocean/provider.go
Labels: approved, lgtm, release-note, size/S, dco-signoff: yes, sig/osm

#1326 Populate default OSP annotation if an empty value is provided for the OSP key
  pkg/admission/machinedeployments_validation.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1329 Fix KubeVirt e2e Os images http server
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1330 Update Go dependencies
  go.mod
  go.sum
  pkg/cloudprovider/provider/anexia/helper_test.go
  pkg/cloudprovider/provider/anexia/instance.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/nutanix/client.go
  pkg/cloudprovider/provider/nutanix/provider.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/L, dco-signoff: yes, sig/osm

#1331 Anexia: increase HTTP client timeout
  pkg/cloudprovider/provider/anexia/provider.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note, ok-to-test, dco-signoff: yes, sig/osm

#1338 Support rockylinux in Equinixmetal cloud provider
  pkg/cloudprovider/provider/equinixmetal/provider.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-equinixmetal.yaml
  test/e2e/provisioning/testdata/machinedeployment-gce.yaml
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes, sig/osm

#1339 Add metro support for equinixmetal
  go.mod
  go.sum
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/equinixmetal/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-equinixmetal.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1341 Upgrade to go 1.18.3
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-fixtures.sh
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes

#1335 Consume bootstrap config generated by OSM
  go.mod
  go.sum
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/util/cloud_init_settings.go
  pkg/cloudprovider/util/cloud_init_settings_test.go
  pkg/controller/machine/bootstrap.go
  pkg/controller/machine/machine_controller.go
  pkg/controller/util/machine.go
  pkg/userdata/amzn2/provider.go
  pkg/userdata/centos/provider.go
  pkg/userdata/helper/helper.go
  pkg/userdata/rhel/provider.go
  pkg/userdata/rockylinux/provider.go
  pkg/userdata/sles/provider.go
  pkg/userdata/ubuntu/provider.go
Labels: sig/cluster-management, size/XL, approved, lgtm, release-note, dco-signoff: yes, sig/osm

#1337 Bump docker version to 20.10
  pkg/containerruntime/docker.go
  pkg/userdata/amzn2/testdata/kubelet-v1.21-aws-external.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-vsphere-mirrors.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-vsphere-proxy.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.21-vsphere.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/amzn2/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.21-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-nutanix.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-nutanix.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.21-aws-external.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.21-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere-mirrors.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere-proxy.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.21-vsphere.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-nutanix.yaml
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/docker.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/nutanix.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.21.10.yaml
  pkg/userdata/ubuntu/testdata/version-1.22.7.yaml
  pkg/userdata/ubuntu/testdata/version-1.23.5.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, sig/osm
