Repository kubermatic/machine-controller, pull requests merged in 2022-09, with the labels that each got.

#1423 Migrate AWS cloud provider to AWS Go SDK v2
  .prow/e2e-features.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/aws/types/types.go
Labels: kind/cleanup, sig/cluster-management, size/XL, approved, lgtm, release-note, dco-signoff: yes, sig/osm

#1426 switch to kubermati-ci folder in e2e tests
  test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes

#1424 Fix to mitigate race condition while configuring kubelet node ips
  pkg/userdata/helper/helper.go
  pkg/userdata/ubuntu/testdata/digitalocean-dualstack.yaml
  pkg/userdata/ubuntu/testdata/openstack-dualstack.yaml
Labels: approved, lgtm, release-note-none, size/S, dco-signoff: yes, sig/osm

#1431 Bump Kubernetes versions used for E2E tests to 1.22.14, 1.23.11 and 1.24.5 respectively
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes

#1435 Add leader election related flags to machine-controller
  cmd/machine-controller/main.go
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes

#1436 Remove references to proxy in Nutanix e2e testing
  .prow/provider-nutanix.yaml
  hack/ci/run-e2e-tests.sh
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-nutanix.yaml
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, release-note-none, size/S, kind/failing-test, dco-signoff: yes

#1430 Fix dualstack IPv6 addr assignment issue in rockylinux and RHEL
  pkg/userdata/rhel/provider.go
  pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-nutanix.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.24-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.24-aws.yaml
  pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
  pkg/userdata/rockylinux/provider.go
  pkg/userdata/rockylinux/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-nutanix.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.24-aws.yaml
Labels: kind/bug, approved, lgtm, release-note-none, size/L, dco-signoff: yes, sig/osm

#1427 Support for Ubuntu 22.04
  docs/operating-system.md
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/containerruntime/docker.go
  pkg/userdata/centos/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-nutanix.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-nutanix.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-nutanix.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/ubuntu/testdata/digitalocean-dualstack.yaml
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/docker.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/nutanix.yaml
  pkg/userdata/ubuntu/testdata/openstack-dualstack.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.22.7.yaml
  pkg/userdata/ubuntu/testdata/version-1.23.5.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, kind/feature, dco-signoff: yes, sig/osm

#1439 Upgrade containerd v1.6
  pkg/containerruntime/containerd.go
  pkg/containerruntime/docker.go
  pkg/userdata/centos/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-nutanix.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/centos/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/centos/testdata/kubelet-v1.24-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.22-nutanix.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.24-aws-external.yaml
  pkg/userdata/rhel/testdata/kubelet-v1.24-aws.yaml
  pkg/userdata/rhel/testdata/pod-cidr-azure-rhel.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-nutanix.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.24-aws.yaml
  pkg/userdata/ubuntu/testdata/containerd.yaml
  pkg/userdata/ubuntu/testdata/digitalocean-dualstack.yaml
  pkg/userdata/ubuntu/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/ubuntu/testdata/docker.yaml
  pkg/userdata/ubuntu/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/ubuntu/testdata/multiple-dns-servers.yaml
  pkg/userdata/ubuntu/testdata/multiple-ssh-keys.yaml
  pkg/userdata/ubuntu/testdata/nutanix.yaml
  pkg/userdata/ubuntu/testdata/openstack-dualstack.yaml
  pkg/userdata/ubuntu/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/ubuntu/testdata/openstack.yaml
  pkg/userdata/ubuntu/testdata/version-1.22.7.yaml
  pkg/userdata/ubuntu/testdata/version-1.23.5.yaml
  pkg/userdata/ubuntu/testdata/version-1.24.0.yaml
  pkg/userdata/ubuntu/testdata/vsphere-mirrors.yaml
  pkg/userdata/ubuntu/testdata/vsphere-proxy.yaml
  pkg/userdata/ubuntu/testdata/vsphere.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm, kind/chore

#1440 Update OSM image for e2e tests
  examples/operating-system-manager.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, kind/chore

#1444 Upgrade to flannel v0.19.2 for E2E tests
  hack/ci/setup-kind-cluster.sh
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, kind/chore

#1449 [release/v1.54] Fix e2e tests for vSphere
  test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, kind/chore

#1451 Add an option to enable nested virtualization and CPU platform for GCP
  examples/gce-machinedeployment.yaml
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/gce/provider_test.go
  pkg/cloudprovider/provider/gce/types/types.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, kind/feature, dco-signoff: yes, sig/osm, docs/none

#1445 add support for topology spread constraint for VMs
  examples/kubevirt-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
  pkg/cloudprovider/provider/kubevirt/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, kind/feature, dco-signoff: yes, sig/virtualization, sig/osm
