Repository kubermatic/machine-controller, pull requests merged in 2022-08, with the labels that each got.

#1386 [release/v1.43] Fix cleanup for machines on azure
  pkg/cloudprovider/provider/azure/create_delete_resources.go
  pkg/cloudprovider/provider/azure/provider.go
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1387 [release/v1.42] Add missing --resolv-conf to kubelet
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.20.14.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.21.8.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.22.5.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.23.0.yaml
  pkg/userdata/flatcar/testdata/containerd.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.20.14.json
  pkg/userdata/flatcar/testdata/ignition_v1.21.8.json
  pkg/userdata/flatcar/testdata/ignition_v1.22.5.json
  pkg/userdata/flatcar/testdata/ignition_v1.23.0.json
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1388 [release/v1.45] Add missing --resolv-conf to kubelet
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.20.14.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.21.8.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.22.5.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.23.0.yaml
  pkg/userdata/flatcar/testdata/containerd.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.20.14.json
  pkg/userdata/flatcar/testdata/ignition_v1.21.8.json
  pkg/userdata/flatcar/testdata/ignition_v1.22.5.json
  pkg/userdata/flatcar/testdata/ignition_v1.23.0.json
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1384 [release/v1.43] Add missing --resolv-conf to kubelet on flatcar
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.20.14.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.21.8.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.22.5.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.23.0.yaml
  pkg/userdata/flatcar/testdata/containerd.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.20.14.json
  pkg/userdata/flatcar/testdata/ignition_v1.21.8.json
  pkg/userdata/flatcar/testdata/ignition_v1.22.5.json
  pkg/userdata/flatcar/testdata/ignition_v1.23.0.json
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1385 Implement ProviderID() for Anexia
  pkg/cloudprovider/provider/anexia/instance.go
Labels: approved, lgtm, size/XS, release-note, ok-to-test, dco-signoff: yes, sig/osm

#1389 fix kubevirt secondary disk naming
  pkg/cloudprovider/provider/kubevirt/provider.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm

#1392 [release/v1.43] Update containerd to v1.5 for all Kubernetes versions
  hack/lib.sh
  hack/update-fixtures.sh
  pkg/containerruntime/containerd.go
  pkg/containerruntime/docker.go
  pkg/userdata/centos/testdata/kubelet-containerd-v1.20-aws.yaml
  pkg/userdata/rhel/testdata/kubelet-containerd-v1.20-aws.yaml
  pkg/userdata/ubuntu/testdata/containerd.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1396 Add `publicIPSKU` field to Azure provider
  .golangci.yml
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/azure/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm

#1398 Unified PR template update
  .github/PULL_REQUEST_TEMPLATE.md
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes

#1399 Fix SLES description
  pkg/cloudprovider/provider/aws/provider.go
Labels: approved, lgtm, size/XS, release-note-none, dco-signoff: yes, sig/osm

#1400 Operating system compatibility matrix update
  docs/operating-system.md
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, release-note-none, size/L, kind/documentation, dco-signoff: yes

#1401 Align KubeVirt cloud config with upstream
  pkg/cloudprovider/provider/kubevirt/provider.go
Labels: kind/cleanup, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, sig/virtualization, sig/osm

#1397 enable DHCPv6 in RockyLinux
  pkg/userdata/rockylinux/provider.go
  pkg/userdata/rockylinux/testdata/kubelet-v1.22-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws-external.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-aws.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-nutanix.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-mirrors.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere-proxy.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.23-vsphere.yaml
  pkg/userdata/rockylinux/testdata/kubelet-v1.24-aws.yaml
Labels: approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm

#1393 set IPv6AcceptRA=true for Flatcar
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.22.7.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.23.5.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.24.0.yaml
  pkg/userdata/flatcar/testdata/containerd.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.22.7.json
  pkg/userdata/flatcar/testdata/ignition_v1.23.5.json
  pkg/userdata/flatcar/testdata/ignition_v1.24.0.json
Labels: approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm

#1404 improve kubeconfig/gcp handling of credentials in e2e tests
  docs/cloud-provider.md
  examples/gce-machinedeployment.yaml
  examples/kubevirt-machinedeployment.yaml
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-gce.yaml
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm

#1407 [release/v1.42] improve kubeconfig/gcp handling of credentials in e2e tests (#1404)
  docs/cloud-provider.md
  examples/gce-machinedeployment.yaml
  examples/kubevirt-machinedeployment.yaml
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-gce.yaml
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm

#1408 [release/v1.43] improve kubeconfig/gcp handling of credentials in e2e tests (#1404)
  docs/cloud-provider.md
  examples/gce-machinedeployment.yaml
  examples/kubevirt-machinedeployment.yaml
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-gce.yaml
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm

#1409 [release/v1.45] improve kubeconfig/gcp handling of credentials in e2e tests (#1404)
  docs/cloud-provider.md
  examples/gce-machinedeployment.yaml
  examples/kubevirt-machinedeployment.yaml
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-gce.yaml
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm

#1402 Anexia: extend disk configuration
  .prow/provider-anexia.yaml
  examples/anexia-machinedeployment.yaml
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/anexia/reconcile_context.go
  pkg/cloudprovider/provider/anexia/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, ok-to-test, dco-signoff: yes, sig/osm

#1412 Fix E2E tests for vSphere and OpenStack
  .prow/provider-vsphere.yaml
  examples/operating-system-manager.yaml
  go.mod
  go.sum
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-vsphere-datastore-cluster.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-resource-pool.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere-static-ip.yaml
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, kind/failing-test, dco-signoff: yes

#1405 [release/v1.45] Improvements for Anexia
  docs/anexia.md
  examples/anexia-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/anexia/helper_test.go
  pkg/cloudprovider/provider/anexia/instance.go
  pkg/cloudprovider/provider/anexia/instance_test.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/anexia/reconcile_context.go
  pkg/cloudprovider/provider/anexia/types/errors.go
  pkg/cloudprovider/provider/anexia/types/types.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/XXL, ok-to-test, kind/feature, dco-signoff: yes, sig/osm

#1410 Anexia: return reserved IP when instance IPs are requested
  pkg/cloudprovider/provider/anexia/instance.go
  pkg/cloudprovider/provider/anexia/instance_test.go
  pkg/cloudprovider/provider/anexia/provider.go
Labels: approved, lgtm, release-note-none, size/L, ok-to-test, kind/feature, dco-signoff: yes, sig/osm

#1416 enable flatcar, rockylinux and rhel for azure
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes

#1406 Makefile: fix test-unit-docker
  Makefile
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/XS, release-note-none, ok-to-test, kind/failing-test, dco-signoff: yes
