Repository kubermatic/machine-controller, pull requests merged in 2023-09, with the labels that each got.

#1703 Update project owners
  OWNERS_ALIASES
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, kind/chore, docs/none

#1705 Update Kubernetes patch versions for E2E tests
  pkg/userdata/helper/common_test.go
  pkg/userdata/helper/testdata/download_binaries_v1.25.14.golden
  pkg/userdata/helper/testdata/download_binaries_v1.26.9.golden
  pkg/userdata/helper/testdata/download_binaries_v1.27.6.golden
  pkg/userdata/helper/testdata/download_binaries_v1.28.2.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.25.14-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.25.14.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.26.9-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.26.9.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.27.6-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.27.6.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.28.2-external.golden
  pkg/userdata/helper/testdata/kublet_systemd_unit_version-v1.28.2.golden
  pkg/userdata/ubuntu/provider_test.go
  pkg/userdata/ubuntu/testdata/version-1.25.14.yaml
  pkg/userdata/ubuntu/testdata/version-1.26.9.yaml
  pkg/userdata/ubuntu/testdata/version-1.27.6.yaml
  pkg/userdata/ubuntu/testdata/version-1.28.2.yaml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none

#1706 Fix isssue of creation of multiple vultr instance due to eventual consistency
  examples/vultr-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/vultr/provider.go
  pkg/cloudprovider/provider/vultr/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, ok-to-test, dco-signoff: yes, docs/none
