Repository kubermatic/machine-controller, pull requests merged in 2023-05, with the labels that each got.

#1628 fix missing formatting in log line
  pkg/node/eviction/eviction.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, docs/none

#1629 relax CSR validation to support Kubernetes 1.27
  pkg/controller/nodecsrapprover/controller.go
  pkg/controller/nodecsrapprover/controller_test.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, docs/none

#1450 Add support for OpenNebula as a cloud provider
  .gitignore
  docs/cloud-provider.md
  examples/opennebula-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/provider/opennebula/provider.go
  pkg/cloudprovider/provider/opennebula/types/types.go
  pkg/providerconfig/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-opennebula.yaml
Labels: sig/cluster-management, size/XL, approved, lgtm, release-note, ok-to-test, kind/feature, dco-signoff: yes, sig/osm, docs/tbd

#1634 [release/v1.56] Update Go to 1.19.9
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-fixtures.sh
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, kind/feature, dco-signoff: yes

#1635 [release/v1.54] Update Go to 1.18.10
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-fixtures.sh
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, kind/feature, dco-signoff: yes

#1633 Update Go to 1.20.4
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-fixtures.sh
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, kind/feature, dco-signoff: yes, docs/none

#1637 Anexia Provider: Configure dns servers
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/anexia/reconcile_context.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, ok-to-test, kind/feature, dco-signoff: yes, docs/none

#1640 [release/v1.56] Anexia Provider: Configure dns servers
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/anexia/reconcile_context.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, kind/feature, dco-signoff: yes

#1641 [release/v1.54] Anexia Provider: Configure dns servers
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/anexia/reconcile_context.go
Labels: approved, lgtm, size/M, release-note, kind/feature, dco-signoff: yes, sig/osm

#1643 E2E: Fix configuration for spot instances on AWS
  test/e2e/provisioning/testdata/machinedeployment-aws-ebs-encryption-enabled.yaml
  test/e2e/provisioning/testdata/machinedeployment-aws-spot-instances.yaml
  test/e2e/provisioning/testdata/machinedeployment-aws.yaml
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, kind/failing-test, dco-signoff: yes, docs/none

#1642 Deprecate user data plugins
  README.md
Labels: sig/cluster-management, approved, lgtm, size/S, release-note-action-required, dco-signoff: yes, kind/deprecation, docs/tbd

#1644 Switch to cert-manager for certificates
  Makefile
  README.md
  cmd/webhook/main.go
  examples/machine-controller.yaml
  hack/ci/setup-machine-controller-in-kind.sh
Labels: sig/cluster-management, approved, lgtm, size/L, release-note-action-required, dco-signoff: yes, kind/chore, docs/none

#1631 Add documentation for community providers
  README.md
  docs/cloud-provider.md
  pkg/cloudprovider/provider.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, kind/documentation, dco-signoff: yes, docs/none

#1646 Fix empty network config handling
  pkg/cloudprovider/provider/anexia/helper_test.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/L, release-note, ok-to-test, dco-signoff: yes, docs/none

#1650 [release/v1.56] Anexia Provider: Fix empty network config handling
  pkg/cloudprovider/provider/anexia/helper_test.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/L, release-note, needs-ok-to-test, dco-signoff: yes
