Repository kubermatic/machine-controller, pull requests merged in 2023-12, with the labels that each got.

#1745 [release/v1.57] Bump Prow jobs and pin KKP version to match release branch
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  hack/ci/setup-kind-cluster.sh
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, kind/chore

#1746 Update Prow jobs to build image with Go 1.21.5
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  examples/operating-system-manager.yaml
  hack/update-fixtures.sh
  hack/verify-licenses.sh
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, kind/chore, docs/none

#1747 [release/v1.58] Update Prow jobs to build image with Go 1.21.5
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  examples/operating-system-manager.yaml
  hack/update-fixtures.sh
  hack/verify-licenses.sh
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, kind/chore

#1748 [release/v1.57] Update Prow jobs to build image with Go 1.20.12
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-fixtures.sh
  hack/verify-licenses.sh
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, kind/chore

#1749 Deprecate sig-virtualization
  OWNERS_ALIASES
  pkg/cloudprovider/provider/kubevirt/OWNERS
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes, sig/virtualization, docs/none

#1740 kubevirt: allow setting storage volume access types
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/types/types.go
Labels: approved, lgtm, size/M, release-note, kind/feature, dco-signoff: yes, sig/virtualization, docs/tbd
