Repository kubermatic/machine-controller, pull requests merged in 2023-01, with the labels that each got.

#1520 Allow specifying full image reference for GCP
  pkg/cloudprovider/provider/gce/config.go
Labels: approved, lgtm, size/XS, release-note, kind/feature, dco-signoff: yes, sig/osm, docs/none

#1523 Disable KubeVirt e2e tests
  .prow/provider-kubevirt.yaml
  test/e2e/provisioning/all_e2e_test.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, docs/none

#1524 support prow-based provider disabling
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  hack/ci/run-e2e-tests.sh
  hack/lib.sh
  test/e2e/provisioning/all_e2e_test.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/L, kind/feature, dco-signoff: yes, docs/none

#1526 exact string match fails, use conventional errors.Is instead
  pkg/cloudprovider/provider/openstack/provider.go
Labels: kind/bug, approved, lgtm, size/XS, release-note, ok-to-test, dco-signoff: yes, sig/osm, docs/none

#1527 KubeVirt fix ci (DC)
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, kind/failing-test, dco-signoff: yes, sig/virtualization, docs/none, test/require-kubevirt

#1525 Drop support for SLES
  .prow/provider-aws.yaml
  Makefile
  cmd/userdata/sles/main.go
  docs/operating-system.md
  examples/aws-machinedeployment.yaml
  examples/azure-machinedeployment.yaml
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/containerruntime/containerd.go
  pkg/containerruntime/docker.go
  pkg/providerconfig/types.go
  pkg/providerconfig/types/types.go
  pkg/userdata/manager/manager.go
  pkg/userdata/sles/provider.go
  pkg/userdata/sles/provider_test.go
  pkg/userdata/sles/sles.go
  pkg/userdata/sles/testdata/dist-upgrade-on-boot.yaml
  pkg/userdata/sles/testdata/kubelet-version-without-v-prefix.yaml
  pkg/userdata/sles/testdata/multiple-dns-servers.yaml
  pkg/userdata/sles/testdata/multiple-ssh-keys.yaml
  pkg/userdata/sles/testdata/openstack-overwrite-cloud-config.yaml
  pkg/userdata/sles/testdata/openstack.yaml
  pkg/userdata/sles/testdata/version-1.24.9.yaml
  pkg/userdata/sles/testdata/version-1.25.5.yaml
  pkg/userdata/sles/testdata/version-1.26.0.yaml
  pkg/userdata/sles/testdata/vsphere-mirrors.yaml
  pkg/userdata/sles/testdata/vsphere-proxy.yaml
  pkg/userdata/sles/testdata/vsphere.yaml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-aws-arm-machines.yaml
  test/e2e/provisioning/testdata/machinedeployment-aws-ebs-encryption-enabled.yaml
  test/e2e/provisioning/testdata/machinedeployment-aws-spot-instances.yaml
  test/e2e/provisioning/testdata/machinedeployment-aws.yaml
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, release-note, size/XXL, dco-signoff: yes, sig/osm, docs/provided

#1529 Refactoring of KubeVirt PVC image source
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
  pkg/cloudprovider/provider/kubevirt/types/types.go
Labels: approved, lgtm, size/L, release-note, kind/feature, dco-signoff: yes, sig/virtualization, docs/none

#1537 Anexia Provider: Return TerminalError on 401 and 403 engine responses
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
Labels: kind/cleanup, approved, lgtm, release-note-none, size/L, ok-to-test, dco-signoff: yes, sig/osm, docs/none

#1532 Refactor vsphere tagging mechanism
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/types/types.go
Labels: approved, lgtm, size/M, release-note, dco-signoff: yes, sig/osm, docs/none

#1543 Remove sig-osm from userdata and cloudprovider ownership
  OWNERS_ALIASES
  pkg/cloudprovider/provider/OWNERS
  pkg/userdata/OWNERS
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/osm, kind/chore, docs/none

#1536 [release/v1.45] Anexia Provider: Utilize `Creating` state instead of blocking `Create` call
  pkg/cloudprovider/provider/anexia/helper_test.go
  pkg/cloudprovider/provider/anexia/instance.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
Labels: kind/cleanup, approved, lgtm, do-not-merge/hold, size/L, release-note, ok-to-test, dco-signoff: yes, sig/osm

#1541 Anexia Provider: add support for named VM templates
  docs/anexia.md
  examples/anexia-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/anexia/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, kind/documentation, kind/api-change, ok-to-test, kind/feature, dco-signoff: yes, sig/osm, docs/provided
