Repository kubermatic/machine-controller, pull requests merged in 2023-02, with the labels that each got.

#1549 Make ID an optional field for vSphere tags
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, kind/design, dco-signoff: yes, docs/none

#1553 Anexia Provider: configure rpc-statd service as kubelet dependency
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.24.0.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.24.9.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.25.0.yaml
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, needs-ok-to-test, kind/feature, dco-signoff: yes, docs/none

#1554 Adjust kubevirt image repo
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, docs/none

#1557 Generate correct node affinity if no values are passed
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
  pkg/cloudprovider/provider/kubevirt/testdata/affinity-no-values.yaml
Labels: kind/bug, approved, lgtm, size/L, release-note, dco-signoff: yes, sig/virtualization, docs/none

#1559 [release/v1.54] Fix Flatcar network issues when IPAM is not used
  pkg/userdata/flatcar/provider.go
Labels: kind/bug, approved, lgtm, size/XS, release-note, dco-signoff: yes, sig/osm

#1561 Always use latest OSM image in e2e tests
  .prow/provider-azure.yaml
  examples/operating-system-manager.yaml
  test/e2e/provisioning/helper.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes, kind/chore, docs/none

#1563 [release/v1.54] Anexia Provider: add support for named VM templates
  docs/anexia.md
  examples/anexia-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/anexia/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, needs-ok-to-test, dco-signoff: yes, sig/osm

#1564 [release/v1.54] Update trigger condition for cloud provider specific E2E jobs
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-openstack.yaml
  .prow/provider-vsphere.yaml
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes, kind/chore

#1565 Use AWS spot instances for tests that always run
  .prow/provider-aws.yaml
  pkg/cloudprovider/provider/anexia/instance_test.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, sig/virtualization, kind/chore, docs/none

#1568 Add providerID support for cloud providers
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/vmwareclouddirector/provider.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note, kind/feature, dco-signoff: yes, docs/none

#1531 Basic support for vultr provider
  .wwhrd.yml
  docs/cloud-provider.md
  examples/vultr-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/provider/vultr/provider.go
  pkg/cloudprovider/provider/vultr/types/types.go
  pkg/providerconfig/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-vultr.yaml
Labels: sig/cluster-management, size/XL, approved, lgtm, release-note, ok-to-test, kind/feature, dco-signoff: yes, sig/osm, docs/tbd

#1570 Increase default timeout for OpenStack provider
  pkg/cloudprovider/provider/openstack/provider.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note, dco-signoff: yes, kind/chore, docs/none

#1572 Add metrics for provisioning nodes
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/metrics.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, ok-to-test, kind/feature, dco-signoff: yes, docs/none

#1571 Anexia Provider: Postpone machine cleanup when instance is still being created
  pkg/cloudprovider/provider/anexia/instance.go
  pkg/cloudprovider/provider/anexia/provider.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, release-note, size/S, ok-to-test, dco-signoff: yes, docs/none

#1575 Backport metrics node provisioning to v1.54
  pkg/controller/machine/machine_controller.go
  pkg/controller/machine/metrics.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, needs-ok-to-test, kind/feature, dco-signoff: yes

#1578 [release/v1.54] Anexia Provider: configure rpc-statd service as kubelet dependency
  pkg/userdata/flatcar/provider.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.22.7.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.23.5.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.24.0.yaml
Labels: approved, lgtm, release-note, size/S, needs-ok-to-test, dco-signoff: yes, sig/osm

#1579 Support Private IP for Hetzner Cloud
  examples/hetzner-machinedeployment.yaml
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/hetzner/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, kind/feature, dco-signoff: yes, docs/none
