Repository kubermatic/machine-controller, pull requests merged in 2023-07, with the labels that each got.

#1673 Support for configuring multiple NICs for vSphere
  docs/vsphere.md
  examples/vsphere-datastore-cluster-machinedeployment.yaml
  examples/vsphere-machinedeployment.yaml
  pkg/cloudprovider/provider/vsphere/helper.go
  pkg/cloudprovider/provider/vsphere/network.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/provider_test.go
  pkg/cloudprovider/provider/vsphere/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-action-required, kind/feature, dco-signoff: yes, docs/none

#1672 KubeVirt: support for OCI VM image source
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
  pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source-pod.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/types/types.go
Labels: approved, lgtm, size/L, release-note, kind/feature, dco-signoff: yes, sig/virtualization, docs/tbd

#1679 [release/v1.54] Fix CI job for license validation
  .prow/verify.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, kind/failing-test, dco-signoff: yes

#1682 Propagate datastore cluster for vSphere to cloud-config
  pkg/cloudprovider/provider/vsphere/provider.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/XS, release-note, dco-signoff: yes, docs/none

#1683 Replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  go.mod
  go.sum
  pkg/apis/cluster/v1alpha1/conversions/conversions_test.go
  pkg/apis/cluster/v1alpha1/conversions/providerconfig_to_providerspec_test.go
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, size/XS, release-note-none, ok-to-test, dco-signoff: yes, kind/chore, docs/none

#1693 Fix version of k8s.io/client-go in go.mod to v0.26.4
  go.mod
  go.sum
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/L, dco-signoff: yes, kind/chore, docs/none
