Repository kubermatic/machine-controller, pull requests merged in 2023-04, with the labels that each got.

#1612 API token authentication support for VMware Cloud Director
  examples/vmware-cloud-director-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/vmwareclouddirector/client.go
  pkg/cloudprovider/provider/vmwareclouddirector/provider.go
  pkg/cloudprovider/provider/vmwareclouddirector/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, kind/feature, dco-signoff: yes, docs/none

#1614 Update Golang version to 1.20.3
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-fixtures.sh
  hack/verify-licenses.sh
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, kind/chore, docs/none

#1616 fix not found check: errors.As for type match whereas errors.Is for value equality
  pkg/cloudprovider/provider/openstack/provider.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/XS, release-note, needs-ok-to-test, dco-signoff: yes, docs/none

#1613 Refactor gcp client creating
  examples/gce-machinedeployment.yaml
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/gce/service.go
  pkg/cloudprovider/provider/gce/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, kind/api-change, kind/feature, dco-signoff: yes, docs/none

#1621 Use eu-central-1b for AWS arm tests
  test/e2e/provisioning/testdata/machinedeployment-aws-arm-machines.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, kind/failing-test, dco-signoff: yes, docs/none

#1611 update container linux config transpiler
  go.mod
  go.sum
  pkg/userdata/convert/ignition-converter.go
  pkg/userdata/flatcar/testdata/ignition_v1.24.0.json
  pkg/userdata/flatcar/testdata/ignition_v1.24.9.json
  pkg/userdata/flatcar/testdata/ignition_v1.25.0.json
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none
