Repository kubermatic/machine-controller, pull requests merged in 2024-11, with the labels that each got.

#1871 replace packethost/packngo with equinix SDK
  go.mod
  go.sum
  pkg/cloudprovider/provider/equinixmetal/provider.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, kind/feature, dco-signoff: yes, docs/none

#1874 Support VM Network Multi-Queue in KubeVirt Provider
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/testdata/affinity-no-values.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/affinity.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/custom-local-disk.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-custom.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-standard.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/kubeovn-provider-network.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/nominal-case.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source-pod.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/secondary-disks.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/topologyspreadconstraints.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/use-storage-as-storage-target.yaml
  pkg/cloudprovider/provider/kubevirt/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, kind/feature, dco-signoff: yes, docs/none

#1880 Refactor Ubuntu ARM image in AWS
  pkg/cloudprovider/provider/aws/provider.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, docs/none
