Repository kubermatic/machine-controller, pull requests merged in 2024-10, with the labels that each got.

#1861 Support Zone-Aware Topology in KubeVirt
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
  pkg/cloudprovider/provider/kubevirt/testdata/location-zone-and-region-aware.yaml
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, docs/none

#1864 Fix: Add reboot action and fix decode cloud-init bug
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/template.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/workflow.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, docs/none

#1863 Support KubeOVN VPC and Subnet
  cmd/machine-controller/main.go
  go.mod
  go.sum
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/providernetworks/kubeovn/provider.go
  pkg/cloudprovider/provider/kubevirt/providernetworks/provider_networks.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, kind/feature, dco-signoff: yes, docs/none

#1865 Revert Changes to KubeVirt Provider Networks
  cmd/machine-controller/main.go
  go.mod
  go.sum
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
  pkg/cloudprovider/provider/kubevirt/providernetworks/kubeovn/provider.go
  pkg/cloudprovider/provider/kubevirt/providernetworks/provider_networks.go
  pkg/cloudprovider/provider/kubevirt/testdata/affinity-no-values.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/affinity.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/custom-local-disk.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-custom.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-standard.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/kubeovn-provider-network.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/nominal-case.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source-pod.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/secondary-disks.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/topologyspreadconstraints.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/use-storage-as-storage-target.yaml
  pkg/cloudprovider/provider/kubevirt/types/types.go
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, release-note-none, size/L, dco-signoff: yes, docs/none

#1866 Fix: Configure Cloud-Init Script to execute automatically
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/template.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, docs/none

#1868 Update to latest k8s patch releases for e2e tests
  examples/alibaba-machinedeployment.yaml
  examples/anexia-machinedeployment.yaml
  examples/aws-machinedeployment.yaml
  examples/azure-machinedeployment.yaml
  examples/digitalocean-machinedeployment.yaml
  examples/equinixmetal-machinedeployment.yaml
  examples/gce-machinedeployment.yaml
  examples/hetzner-machinedeployment.yaml
  examples/kubevirt-machinedeployment.yaml
  examples/linode-machinedeployment.yaml
  examples/nutanix-machinedeployment.yaml
  examples/opennebula-machinedeployment.yaml
  examples/openstack-machinedeployment.yaml
  examples/scaleway-machinedeployment.yaml
  examples/vmware-cloud-director-machinedeployment.yaml
  examples/vsphere-datastore-cluster-machinedeployment.yaml
  examples/vsphere-machinedeployment.yaml
  examples/vultr-machinedeployment.yaml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-azure-redhat-satellite.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none

#1869 Fix typo in template.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/template.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, docs/none

#1858 Support Ubuntu 24.04
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/hetzner/provider.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes, docs/none

#1870 Drop support for Kubernetes v1.28
  README.md
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes, docs/none

#1872 Refactor kubervirt provider storage
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
  pkg/cloudprovider/provider/kubevirt/testdata/affinity-no-values.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/affinity.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/custom-local-disk.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-custom.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-standard.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/kubeovn-provider-network.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/nominal-case.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source-pod.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/secondary-disks.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/topologyspreadconstraints.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/use-storage-as-storage-target.yaml
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, kind/feature, dco-signoff: yes, docs/none
