Repository kubermatic/machine-controller, pull requests merged in 2024-07, with the labels that each got.

#1822 Bump Go version to 1.22.5
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-fixtures.sh
  hack/verify-licenses.sh
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, kind/chore, docs/none

#1824 Update to latest k8s patch releases for e2e tests
  .prow/provider-vmware-cloud-director.yaml
  examples/alibaba-machinedeployment.yaml
  examples/anexia-machinedeployment.yaml
  examples/aws-machinedeployment.yaml
  examples/azure-machinedeployment.yaml
  examples/digitalocean-machinedeployment.yaml
  examples/equinixmetal-machinedeployment.yaml
  examples/gce-machinedeployment.yaml
  examples/hetzner-machinedeployment.yaml
  examples/kubevirt-machinedeployment.yaml
  examples/linode-machinedeployment.yaml
  examples/nutanix-machinedeployment.yaml
  examples/opennebula-machinedeployment.yaml
  examples/openstack-machinedeployment.yaml
  examples/scaleway-machinedeployment.yaml
  examples/vmware-cloud-director-machinedeployment.yaml
  examples/vsphere-datastore-cluster-machinedeployment.yaml
  examples/vsphere-machinedeployment.yaml
  examples/vultr-machinedeployment.yaml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-azure-redhat-satellite.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none

#1825 Update dependencies
  .golangci.yml
  .wwhrd.yml
  go.mod
  go.sum
  pkg/cloudprovider/provider/scaleway/provider.go
Labels: kind/cleanup, sig/cluster-management, size/XL, approved, lgtm, release-note-none, dco-signoff: yes, kind/chore, docs/none

#1823 Remove Kubernetes 1.27 support
  README.md
  pkg/controller/machine/controller.go
  pkg/providerconfig/types/types.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, docs/tbd

#1828 Cleanup for golangci config
  .golangci.yml
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, docs/none

#1829 OpenStack: Support enabling config drive
  docs/cloud-provider.md
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/provider_test.go
  pkg/cloudprovider/provider/openstack/types/types.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, kind/feature, dco-signoff: yes, docs/none

#1830 Refactor Tinkerbell provider
  examples/baremetal-tinkerbell-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/baremetal/plugins/driver.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/hardware.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/interface.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/template.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/utils.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/workflow.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver_test.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/hardware.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/metadata/client.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/template.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/types/hardware.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/types/types.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/provider/baremetal/types/types.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/XXL, dco-signoff: yes, docs/none

#1832 Fix Hardware Metadata Condition for Tinkerbell Provider
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, docs/none

#1831 Refactor bare metal provider machine cleanup
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/hardware.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/client/workflow.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/driver.go
  pkg/cloudprovider/provider/baremetal/plugins/tinkerbell/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, docs/none

#1833 AWS: Increase HttpPutResponseHopLimit to 3 for EC2 instances
  pkg/cloudprovider/provider/aws/provider.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/XS, release-note, dco-signoff: yes, docs/none
