Repository kubermatic/machine-controller, pull requests merged in 2024-06, with the labels that each got.

#1801 Fix AMI filter for rocky linux
  pkg/cloudprovider/provider/aws/provider.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/XS, release-note, dco-signoff: yes, docs/none

#1803 Update AMI filter for rocky linux
  pkg/cloudprovider/provider/aws/provider.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, kind/chore, docs/none

#1809 [release/v1.59] Update AMI filter for rocky linux (#1803)
  hack/ci/setup-kind-cluster.sh
  pkg/cloudprovider/provider/aws/provider.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes, kind/chore

#1807 [release/v1.57] Update AMI filter for rocky linux (#1803) / Bump OSM to 1.3.6
  examples/operating-system-manager.yaml
  pkg/cloudprovider/provider/aws/provider.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes, kind/chore

#1791 Delete provSpec redundant check in MC providers
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/opennebula/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/cloudprovider/provider/vmwareclouddirector/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vultr/provider.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, dco-signoff: yes, docs/none

#1802 Drop cloud provider specific cloud-configs
  docs/howto-provider.md
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/aws/types/cloudconfig.go
  pkg/cloudprovider/provider/aws/types/cloudconfig_test.go
  pkg/cloudprovider/provider/aws/types/testdata/simple-config.golden
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/azure/types/cloudconfig.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/edge/provider.go
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/gce/types/cloudconfig.go
  pkg/cloudprovider/provider/gce/types/cloudconfig_test.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/types/cloudconfig.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/opennebula/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/types/cloudconfig.go
  pkg/cloudprovider/provider/openstack/types/cloudconfig_test.go
  pkg/cloudprovider/provider/openstack/types/testdata/bs-defaulting-config.golden
  pkg/cloudprovider/provider/openstack/types/testdata/config-with-special-chars.golden
  pkg/cloudprovider/provider/openstack/types/testdata/simple-config.golden
  pkg/cloudprovider/provider/openstack/types/testdata/use-application-credentials-ignore-userpass.golden
  pkg/cloudprovider/provider/openstack/types/testdata/use-application-credentials.golden
  pkg/cloudprovider/provider/openstack/types/testdata/use-octavia-explicitly-disabled.golden
  pkg/cloudprovider/provider/openstack/types/testdata/use-octavia-explicitly-enabled.golden
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/cloudprovider/provider/vmwareclouddirector/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/types/cloudconfig.go
  pkg/cloudprovider/provider/vsphere/types/cloudconfig_test.go
  pkg/cloudprovider/provider/vsphere/types/testdata/2-virtual-centers.golden
  pkg/cloudprovider/provider/vsphere/types/testdata/3-dual-stack.golden
  pkg/cloudprovider/provider/vsphere/types/testdata/simple-config.golden
  pkg/cloudprovider/provider/vultr/provider.go
  pkg/cloudprovider/types/types.go
  pkg/cloudprovider/validationwrapper.go
  pkg/userdata/cloud/provider.go
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, release-note, size/XXL, dco-signoff: yes, docs/none

#1806 Bump Go version to 1.22.4
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/ci/calico.yaml
  hack/update-fixtures.sh
  hack/verify-licenses.sh
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, kind/chore, docs/none

#1812 Remove container runtime related code
  cmd/machine-controller/main.go
  cmd/provision/README.md
  cmd/webhook/main.go
  go.mod
  go.sum
  pkg/containerruntime/config.go
  pkg/containerruntime/config_test.go
  pkg/containerruntime/containerd.go
  pkg/containerruntime/containerruntime.go
  pkg/containerruntime/flags.go
  pkg/controller/machine/controller.go
  pkg/ini/duration.go
  pkg/ini/escape.go
  pkg/ini/escape_test.go
  pkg/node/flags.go
Labels: kind/cleanup, sig/cluster-management, approved, lgtm, release-note, size/XXL, dco-signoff: yes, docs/tbd

#1814 Deprecate cluster-dns flag
  cmd/machine-controller/main.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, kind/chore, docs/none

#1818 Hetzner: Skip operating system validation if custom image is provided
  pkg/cloudprovider/provider/hetzner/provider.go
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, needs-ok-to-test, dco-signoff: yes, docs/none

#1816 Support for Hetzner arm64 architecture instances
  go.mod
  go.sum
  pkg/cloudprovider/provider/hetzner/provider.go
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, ok-to-test, kind/feature, dco-signoff: yes, docs/none
