Repository kubermatic/machine-controller, pull requests merged in 2024-08, with the labels that each got.

#1838 bump to Go 1.23.0
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  hack/update-fixtures.sh
  hack/verify-licenses.sh
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/controller/util/machine_deployment.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, kind/chore, docs/none

#1839 bump Dockerfile to golang 1.23.0
  Dockerfile
  Makefile
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, docs/none

#1840 Add support for Kubernetes v1.31
  README.md
  examples/alibaba-machinedeployment.yaml
  examples/anexia-machinedeployment.yaml
  examples/aws-machinedeployment.yaml
  examples/azure-machinedeployment.yaml
  examples/digitalocean-machinedeployment.yaml
  examples/equinixmetal-machinedeployment.yaml
  examples/gce-machinedeployment.yaml
  examples/hetzner-machinedeployment.yaml
  examples/kubevirt-machinedeployment.yaml
  examples/linode-machinedeployment.yaml
  examples/nutanix-machinedeployment.yaml
  examples/opennebula-machinedeployment.yaml
  examples/openstack-machinedeployment.yaml
  examples/scaleway-machinedeployment.yaml
  examples/vmware-cloud-director-machinedeployment.yaml
  examples/vsphere-datastore-cluster-machinedeployment.yaml
  examples/vsphere-machinedeployment.yaml
  examples/vultr-machinedeployment.yaml
  go.mod
  go.sum
  pkg/controller/machine/controller.go
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-azure-redhat-satellite.yaml
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, kind/feature, dco-signoff: yes, docs/none

#1843 Remove CentOS tests
  .prow/provider-aws.yaml
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-digitalocean.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note-none, kind/failing-test, dco-signoff: yes, docs/none

#1845 Anexia: extend network configuration to allow multi-interface and multi-IP
  examples/anexia-machinedeployment.yaml
  pkg/cloudprovider/provider/anexia/helper_test.go
  pkg/cloudprovider/provider/anexia/network_provisioning.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/anexia/resolve_config.go
  pkg/cloudprovider/provider/anexia/types/types.go
Labels: sig/cluster-management, size/XL, approved, lgtm, release-note, ok-to-test, kind/feature, dco-signoff: yes, docs/none

#1847 vSphere: support for VM Groups
  .gitignore
  .golangci.yml
  examples/vsphere-machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/types/types.go
  pkg/cloudprovider/provider/vsphere/vmgroup.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, kind/feature, dco-signoff: yes, docs/none

#1844 Fix vSphere E2E tests
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/testdata/machinedeployment-vsphere.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, kind/failing-test, dco-signoff: yes, docs/none

#1848 add kubermatic to packngo User-Agent
  pkg/cloudprovider/provider/equinixmetal/provider.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, ok-to-test, dco-signoff: yes, docs/none

#1849 Add Navid as a machine controller maintainer
  OWNERS_ALIASES
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, docs/none

#1852 disable kubevirt tests and connection to dev is fixed
  .prow/provider-kubevirt.yaml
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, docs/none

#1851 Add static up support for KubeVirt in KubeOVN
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/testdata/affinity-no-values.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/affinity.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/custom-local-disk.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/http-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-custom.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/instancetype-preference-standard.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/nominal-case.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/pvc-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source-pod.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/registry-image-source.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/secondary-disks.yaml
  pkg/cloudprovider/provider/kubevirt/testdata/topologyspreadconstraints.yaml
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, kind/feature, dco-signoff: yes, docs/none

#1853 Copy annotations to KV VMI
  pkg/cloudprovider/provider/kubevirt/provider.go
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note, kind/feature, dco-signoff: yes, docs/none

#1850 Add sig-cluster-management as code owners
  OWNERS
  OWNERS_ALIASES
Labels: sig/cluster-management, approved, lgtm, size/XS, release-note-none, dco-signoff: yes, kind/chore, docs/none
