Repository kubermatic/machine-controller, pull requests merged in 2024-05, with the labels that each got.

#1792 Fix namespace for Machinesets
  pkg/controller/util/machine.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/XS, release-note, dco-signoff: yes, docs/none

#1797 Anexia: various patches (request/response logging, CPU performance type, 404 fix on delete)
  examples/anexia-machinedeployment.yaml
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/types/types.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/M, release-note, needs-ok-to-test, kind/feature, dco-signoff: yes, docs/none

#1786 update to controller-runtime 0.18
  go.mod
  go.sum
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/edge/provider.go
  pkg/controller/machine/controller.go
  pkg/controller/machinedeployment/controller.go
  pkg/controller/machineset/controller.go
  pkg/controller/nodecsrapprover/controller.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, kind/chore, docs/none
