Repository kubermatic/machine-controller, pull requests merged in 2024-02, with the labels that each got.

#1759 Upgrade to Go 1.22
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  examples/operating-system-manager.yaml
  go.mod
  go.sum
  hack/update-fixtures.sh
  hack/verify-licenses.sh
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, kind/chore, docs/none

#1760 Remove TORCX_BINDIR from containerd binary call
  pkg/containerruntime/containerd.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.26.6.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.28.5.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.29.0.yaml
  pkg/userdata/flatcar/testdata/containerd.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.26.6.json
  pkg/userdata/flatcar/testdata/ignition_v1.28.5.json
  pkg/userdata/flatcar/testdata/ignition_v1.29.0.json
Labels: kind/bug, sig/cluster-management, approved, lgtm, release-note, size/S, dco-signoff: yes, docs/none

#1765 Support Edge Provider in Machine Controller
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/provider/edge/provider.go
  pkg/providerconfig/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, kind/feature, dco-signoff: yes, docs/none

#1762 [release/v1.57] Remove TORCX_BINDIR from containerd binary call
  .prow/verify.yaml
  Makefile
  examples/operating-system-manager.yaml
  pkg/containerruntime/containerd.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.24.0.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.24.9.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.25.0.yaml
  pkg/userdata/flatcar/testdata/containerd.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.24.0.json
  pkg/userdata/flatcar/testdata/ignition_v1.24.9.json
  pkg/userdata/flatcar/testdata/ignition_v1.25.0.json
  test/e2e/provisioning/all_e2e_test.go
  test/e2e/provisioning/helper.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes

#1761 [release/v1.58] Remove TORCX_BINDIR from containerd binary call
  .prow/verify.yaml
  Makefile
  examples/operating-system-manager.yaml
  hack/ci/setup-machine-controller-in-kind.sh
  pkg/containerruntime/containerd.go
  pkg/userdata/flatcar/testdata/cloud-init_v1.26.6.yaml
  pkg/userdata/flatcar/testdata/cloud-init_v1.28.0.yaml
  pkg/userdata/flatcar/testdata/containerd.yaml
  pkg/userdata/flatcar/testdata/ignition_v1.26.6.json
  pkg/userdata/flatcar/testdata/ignition_v1.28.0.json
  test/e2e/provisioning/helper.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes
