Repository kubermatic/machine-controller, pull requests merged in 2025-04, with the labels that each got.

#1912 fix kubevirt cpu check + update sdk version in go.mod
  pkg/cloudprovider/provider/kubevirt/provider.go
Labels: kind/bug, sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes, docs/none

#1913 Bump Go version to 1.23.7
  .prow/e2e-features.yaml
  .prow/postsubmits.yaml
  .prow/provider-alibaba.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-equinix-metal.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-linode.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-scaleway.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-fixtures.sh
  hack/verify-licenses.sh
Labels: sig/cluster-management, approved, lgtm, size/M, release-note, dco-signoff: yes, kind/chore, docs/none

#1915 Improve SDK, add readme
  pkg/admission/machines.go
  pkg/cloudprovider/provider.go
  pkg/cloudprovider/provider/alibaba/provider.go
  pkg/cloudprovider/provider/anexia/provider.go
  pkg/cloudprovider/provider/anexia/provider_test.go
  pkg/cloudprovider/provider/anexia/resolve_config.go
  pkg/cloudprovider/provider/aws/provider.go
  pkg/cloudprovider/provider/azure/provider.go
  pkg/cloudprovider/provider/baremetal/provider.go
  pkg/cloudprovider/provider/digitalocean/provider.go
  pkg/cloudprovider/provider/edge/provider.go
  pkg/cloudprovider/provider/equinixmetal/provider.go
  pkg/cloudprovider/provider/external/provider.go
  pkg/cloudprovider/provider/fake/provider.go
  pkg/cloudprovider/provider/gce/config.go
  pkg/cloudprovider/provider/gce/provider.go
  pkg/cloudprovider/provider/gce/provider_test.go
  pkg/cloudprovider/provider/hetzner/provider.go
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
  pkg/cloudprovider/provider/linode/provider.go
  pkg/cloudprovider/provider/nutanix/provider.go
  pkg/cloudprovider/provider/opennebula/provider.go
  pkg/cloudprovider/provider/openstack/provider.go
  pkg/cloudprovider/provider/openstack/provider_test.go
  pkg/cloudprovider/provider/scaleway/provider.go
  pkg/cloudprovider/provider/vmwareclouddirector/provider.go
  pkg/cloudprovider/provider/vsphere/provider.go
  pkg/cloudprovider/provider/vsphere/provider_test.go
  pkg/cloudprovider/provider/vultr/provider.go
  pkg/controller/machine/controller.go
  pkg/controller/machine/metrics.go
  pkg/migrations/migrations.go
  sdk/README.md
  sdk/providerconfig/configvar/resolver.go
  sdk/providerconfig/resolver.go
  test/e2e/provisioning/migrateuidscenario.go
Labels: sig/cluster-management, size/XL, approved, lgtm, release-note-none, kind/api-change, dco-signoff: yes, docs/none

#1916 [release/v1.61] Cherry pick 1906 to release/v1.61
  pkg/cloudprovider/provider/kubevirt/provider.go
  pkg/cloudprovider/provider/kubevirt/provider_test.go
  pkg/cloudprovider/provider/kubevirt/testdata/dedicated-vcpus.yaml
  pkg/cloudprovider/provider/kubevirt/types/types.go
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes

#1917 Update to controller-runtime 0.20, bump golang.org/x libraries
  go.mod
  go.sum
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, dco-signoff: yes, kind/chore, docs/none
