Repository kubermatic/machine-controller, pull requests merged in 2025-09, with the labels that each got.

#1959 [release/v1.61] Use flatcar-container-linux-corevm-amd64 for flatcar on Azure
  pkg/cloudprovider/provider/azure/provider.go
Labels: sig/cluster-management, approved, lgtm, release-note, size/S, kind/feature, dco-signoff: yes

#1964 update rockylinux and rhel image for e2e tests
  test/e2e/provisioning/helper.go
  test/e2e/provisioning/testdata/machinedeployment-kubevirt.yaml
Labels: sig/cluster-management, approved, lgtm, release-note-none, size/S, dco-signoff: yes, kind/chore, docs/none

#1941 Add support to provisioning vcloud workers with multiple nics/networks
  pkg/admission/machinedeployments_validation.go
  pkg/admission/util.go
  pkg/cloudprovider/provider/vmwareclouddirector/helper.go
  pkg/cloudprovider/provider/vmwareclouddirector/provider.go
  sdk/cloudprovider/vmwareclouddirector/types.go
  test/e2e/provisioning/testdata/machinedeployment-vmware-cloud-director.yaml
Labels: sig/cluster-management, approved, lgtm, size/L, release-note, ok-to-test, kind/feature, dco-signoff: yes, docs/tbd
